UPDATE Buildings
SET NationalPopRequired = (SELECT NationalPopRequired FROM Buildings WHERE Type = 'BUILDING_NATIONAL_TREASURY'), Help = 'TXT_KEY_BUILDING_GILGAMESH_VAULT_HELP_CBP'
WHERE Type = 'BUILDING_GILGAMESH_VAULT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_NATIONAL_WONDERS' AND Value= 1 );

UPDATE Building_PrereqBuildingClasses
SET NumBuildingNeeded = 1
WHERE BuildingType = 'BUILDING_GILGAMESH_VAULT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_NATIONAL_WONDERS' AND Value= 1 );