CREATE TABLE IF NOT EXISTS COMMUNITY(Type, Value);

UPDATE Traits
SET GreatPersonGiftInfluence=0, DOFGreatPersonModifier=0,FreeUnit='UNITCLASS_GREAT_GENERAL',FreeUnitPrereqTech='TECH_MILITARY_SCIENCE'
WHERE (Type = 'TRAIT_DIPLOMACY_GREAT_PEOPLE') AND NOT EXISTS(SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_LEADERS' AND Value= 1);

INSERT INTO Trait_PMMM_PromotionAdjacentUnitCombats
			(TraitType, 						AdjacentDifferentUnitCombatsRequired,	PromotionType)
SELECT		('TRAIT_DIPLOMACY_GREAT_PEOPLE'),	2,										('PROMOTION_PMMM_GUSTAVUS_TRAIT')
WHERE NOT EXISTS(SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_LEADERS' AND Value= 1);


UPDATE Traits
SET Description = 'TXT_KEY_TRAIT_DIPLOMACY_GREAT_PEOPLE_PMMM', ShortDescription = 'TXT_KEY_TRAIT_DIPLOMACY_GREAT_PEOPLE_PMMM_SHORT'
WHERE Type = 'TRAIT_DIPLOMACY_GREAT_PEOPLE' AND NOT EXISTS(SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_LEADERS' AND Value= 1);