INSERT INTO IconTextureAtlases 
			(Atlas, 											IconSize, 	Filename, 							IconsPerRow, 	IconsPerColumn)
			-------------------Color-----------------------------------------------------------------------------------------------------------
VALUES		('CIV_COLOR_ATLAS_DEMON_HOMURA', 					256, 		'HomuraRebellionIconAtlas256.dds',				4, 				1),
			('CIV_COLOR_ATLAS_DEMON_HOMURA', 					128, 		'HomuraRebellionIconAtlas128.dds',				4, 				1),
			('CIV_COLOR_ATLAS_DEMON_HOMURA', 					80, 		'HomuraRebellionIconAtlas80.dds',				4, 				1),
			('CIV_COLOR_ATLAS_DEMON_HOMURA', 					64, 		'HomuraRebellionIconAtlas64.dds',				4, 				1),
			('CIV_COLOR_ATLAS_DEMON_HOMURA', 					45, 		'HomuraRebellionIconAtlas45.dds',				4, 				1),
			('CIV_COLOR_ATLAS_DEMON_HOMURA', 					32, 		'HomuraRebellionIconAtlas32.dds',				4, 				1),
			('CIV_COLOR_ATLAS_MADOKA', 							256, 		'MadokaIconAtlas256.dds',						4, 				2),
			('CIV_COLOR_ATLAS_MADOKA', 							128, 		'MadokaIconAtlas128.dds',						4, 				2),
			('CIV_COLOR_ATLAS_MADOKA', 							80, 		'MadokaIconAtlas80.dds',						4, 				2),
			('CIV_COLOR_ATLAS_MADOKA', 							64, 		'MadokaIconAtlas64.dds',						4, 				2),
			('CIV_COLOR_ATLAS_MADOKA', 							45, 		'MadokaIconAtlas45.dds',						4, 				2),
			('CIV_COLOR_ATLAS_MADOKA', 							32, 		'MadokaIconAtlas32.dds',						4, 				2),
			('CIV_COLOR_ATLAS_MADOKA_TEMP', 					256, 		'MadokaIconAtlasNew256.dds',					4, 				1),
			('CIV_COLOR_ATLAS_MADOKA_TEMP', 					128, 		'MadokaIconAtlasNew128.dds',					4, 				1),
			('CIV_COLOR_ATLAS_MADOKA_TEMP', 					80, 		'MadokaIconAtlasNew80.dds',						4, 				1),
			('CIV_COLOR_ATLAS_MADOKA_TEMP', 					64, 		'MadokaIconAtlasNew64.dds',						4, 				1),
			('CIV_COLOR_ATLAS_MADOKA_TEMP', 					45, 		'MadokaIconAtlasNew45.dds',						4, 				1),
			('CIV_COLOR_ATLAS_MADOKA_TEMP', 					32, 		'MadokaIconAtlasNew32.dds',						4, 				1),
			('CIV_COLOR_ATLAS_HOMURA', 							256, 		'HomuraIconAtlas256.dds',						4, 				1),
			('CIV_COLOR_ATLAS_HOMURA', 							128, 		'HomuraIconAtlas128.dds',						4, 				1),
			('CIV_COLOR_ATLAS_HOMURA', 							80, 		'HomuraIconAtlas80.dds',						4, 				1),
			('CIV_COLOR_ATLAS_HOMURA', 							64, 		'HomuraIconAtlas64.dds',						4, 				1),
			('CIV_COLOR_ATLAS_HOMURA', 							45, 		'HomuraIconAtlas45.dds',						4, 				1),
			('CIV_COLOR_ATLAS_HOMURA', 							32, 		'HomuraIconAtlas32.dds',						4, 				1),
			('CIV_COLOR_ATLAS_SAYAKA', 							256, 		'SayakaIconAtlas256.dds',						4, 				1),
			('CIV_COLOR_ATLAS_SAYAKA', 							128, 		'SayakaIconAtlas128.dds',						4, 				1),
			('CIV_COLOR_ATLAS_SAYAKA', 							80, 		'SayakaIconAtlas80.dds',						4, 				1),
			('CIV_COLOR_ATLAS_SAYAKA', 							64, 		'SayakaIconAtlas64.dds',						4, 				1),
			('CIV_COLOR_ATLAS_SAYAKA', 							45, 		'SayakaIconAtlas45.dds',						4, 				1),
			('CIV_COLOR_ATLAS_SAYAKA', 							32, 		'SayakaIconAtlas32.dds',						4, 				1),
			('CIV_COLOR_ATLAS_MAMI', 							256, 		'MamiIconAtlas256.dds',							4, 				1),
			('CIV_COLOR_ATLAS_MAMI', 							128, 		'MamiIconAtlas128.dds',							4, 				1),
			('CIV_COLOR_ATLAS_MAMI', 							80, 		'MamiIconAtlas80.dds',							4, 				1),
			('CIV_COLOR_ATLAS_MAMI', 							64, 		'MamiIconAtlas64.dds',							4, 				1),
			('CIV_COLOR_ATLAS_MAMI', 							45, 		'MamiIconAtlas45.dds',							4, 				1),
			('CIV_COLOR_ATLAS_MAMI', 							32, 		'MamiIconAtlas32.dds',							4, 				1),
			('CIV_COLOR_ATLAS_KYOUKO', 							256, 		'KyoukoIconAtlas256.dds',						4, 				1),
			('CIV_COLOR_ATLAS_KYOUKO', 							128, 		'KyoukoIconAtlas128.dds',						4, 				1),
			('CIV_COLOR_ATLAS_KYOUKO', 							80, 		'KyoukoIconAtlas80.dds',						4, 				1),
			('CIV_COLOR_ATLAS_KYOUKO', 							64, 		'KyoukoIconAtlas64.dds',						4, 				1),
			('CIV_COLOR_ATLAS_KYOUKO', 							45, 		'KyoukoIconAtlas45.dds',						4, 				1),
			('CIV_COLOR_ATLAS_KYOUKO', 							32, 		'KyoukoIconAtlas32.dds',						4, 				1),
			('CIV_COLOR_ATLAS_NAGISA', 							256, 		'NagisaIconAtlas256.dds',						4, 				1),
			('CIV_COLOR_ATLAS_NAGISA', 							128, 		'NagisaIconAtlas128.dds',						4, 				1),
			('CIV_COLOR_ATLAS_NAGISA', 							80, 		'NagisaIconAtlas80.dds',						4, 				1),
			('CIV_COLOR_ATLAS_NAGISA', 							64, 		'NagisaIconAtlas64.dds',						4, 				1),
			('CIV_COLOR_ATLAS_NAGISA', 							45, 		'NagisaIconAtlas45.dds',						4, 				1),
			('CIV_COLOR_ATLAS_NAGISA', 							32, 		'NagisaIconAtlas32.dds',						4, 				1),
			('CIV_COLOR_ATLAS_ORIGINAL_MADOKA', 				256, 		'OriginalMadokaIconAtlas256.dds',				4, 				1),
			('CIV_COLOR_ATLAS_ORIGINAL_MADOKA', 				128, 		'OriginalMadokaIconAtlas128.dds',				4, 				1),
			('CIV_COLOR_ATLAS_ORIGINAL_MADOKA', 				80, 		'OriginalMadokaIconAtlas80.dds',				4, 				1),
			('CIV_COLOR_ATLAS_ORIGINAL_MADOKA', 				64, 		'OriginalMadokaIconAtlas64.dds',				4, 				1),
			('CIV_COLOR_ATLAS_ORIGINAL_MADOKA', 				45, 		'OriginalMadokaIconAtlas45.dds',				4, 				1),
			('CIV_COLOR_ATLAS_ORIGINAL_MADOKA', 				32, 		'OriginalMadokaIconAtlas32.dds',				4, 				1),
			('CIV_COLOR_ATLAS_KAORU_UMIKA', 					256, 		'PleiadesIconAtlas256.dds',						5, 				1),
			('CIV_COLOR_ATLAS_KAORU_UMIKA', 					128, 		'PleiadesIconAtlas128.dds',						5, 				1),
			('CIV_COLOR_ATLAS_KAORU_UMIKA', 					80, 		'PleiadesIconAtlas80.dds',						5, 				1),
			('CIV_COLOR_ATLAS_KAORU_UMIKA', 					64, 		'PleiadesIconAtlas64.dds',						5, 				1),
			('CIV_COLOR_ATLAS_KAORU_UMIKA', 					45, 		'PleiadesIconAtlas45.dds',						5, 				1),
			('CIV_COLOR_ATLAS_KAORU_UMIKA', 					32, 		'PleiadesIconAtlas32.dds',						5, 				1),
			('CIV_COLOR_ATLAS_ORIKO_KIRIKA', 					256, 		'ShiromeAtlas256.dds',							4, 				1),
			('CIV_COLOR_ATLAS_ORIKO_KIRIKA', 					128, 		'ShiromeAtlas128.dds',							4, 				1),
			('CIV_COLOR_ATLAS_ORIKO_KIRIKA', 					80, 		'ShiromeAtlas80.dds',							4, 				1),
			('CIV_COLOR_ATLAS_ORIKO_KIRIKA', 					64, 		'ShiromeAtlas64.dds',							4, 				1),
			('CIV_COLOR_ATLAS_ORIKO_KIRIKA', 					45, 		'ShiromeAtlas45.dds',							4, 				1),
			('CIV_COLOR_ATLAS_ORIKO_KIRIKA', 					32, 		'ShiromeAtlas32.dds',							4, 				1),

			('UNIT_COLOR_ATLAS_PMMM_WITCH', 					256, 		'WitchIconAtlas256.dds',						4, 				1),
			('UNIT_COLOR_ATLAS_PMMM_WITCH', 					128, 		'WitchIconAtlas128.dds',						4, 				1),
			('UNIT_COLOR_ATLAS_PMMM_WITCH', 					80, 		'WitchIconAtlas80.dds',							4, 				1),
			('UNIT_COLOR_ATLAS_PMMM_WITCH', 					64, 		'WitchIconAtlas64.dds',							4, 				1),
			('UNIT_COLOR_ATLAS_PMMM_WITCH', 					45, 		'WitchIconAtlas45.dds',							4, 				1),
			('UNIT_COLOR_ATLAS_PMMM_WITCH', 					32, 		'WitchIconAtlas32.dds',							4, 				1),
			('UNIT_COLOR_ATLAS_PMMM_INCUBATOR', 				256, 		'IncubatorIconAtlas256.dds',					1, 				1),
			('UNIT_COLOR_ATLAS_PMMM_INCUBATOR', 				128, 		'IncubatorIconAtlas128.dds',					1, 				1),
			('UNIT_COLOR_ATLAS_PMMM_INCUBATOR', 				80, 		'IncubatorIconAtlas80.dds',						1, 				1),
			('UNIT_COLOR_ATLAS_PMMM_INCUBATOR', 				64, 		'IncubatorIconAtlas64.dds',						1, 				1),
			('UNIT_COLOR_ATLAS_PMMM_INCUBATOR', 				45, 		'IncubatorIconAtlas45.dds',						1, 				1),
			('UNIT_COLOR_ATLAS_PMMM_INCUBATOR', 				32, 		'IncubatorIconAtlas32.dds',						1, 				1),
			--------------------------Civ Alphas-----------------------------------------------------------------------------------------------
			('CIV_ALPHA_ATLAS_DEMON_HOMURA', 				128, 		'HomuraRebellionAlpha128.dds',		1, 				1),
			('CIV_ALPHA_ATLAS_DEMON_HOMURA', 				80, 		'HomuraRebellionAlpha80.dds',		1, 				1),
			('CIV_ALPHA_ATLAS_DEMON_HOMURA', 				64, 		'HomuraRebellionAlpha64.dds',		1, 				1),
			('CIV_ALPHA_ATLAS_DEMON_HOMURA', 				48, 		'HomuraRebellionAlpha48.dds',		1, 				1),
			('CIV_ALPHA_ATLAS_DEMON_HOMURA', 				32, 		'HomuraRebellionAlpha32.dds',		1, 				1),
			('CIV_ALPHA_ATLAS_DEMON_HOMURA', 				24, 		'HomuraRebellionAlpha24.dds',		1, 				1),
			('CIV_ALPHA_ATLAS_DEMON_HOMURA', 				16, 		'HomuraRebellionAlpha16.dds',		1, 				1),
			('CIV_ALPHA_ATLAS_MADOKA', 						128, 		'MadokaCivAlpha128.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_MADOKA', 						80, 		'MadokaCivAlpha80.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_MADOKA', 						64, 		'MadokaCivAlpha64.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_MADOKA',						48, 		'MadokaCivAlpha48.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_MADOKA',						32, 		'MadokaCivAlpha32.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_MADOKA',						24, 		'MadokaCivAlpha24.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_MADOKA',						16, 		'MadokaCivAlpha16.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_HOMURA', 						128, 		'HomuraCivAlpha128.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_HOMURA', 						80, 		'HomuraCivAlpha80.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_HOMURA', 						64, 		'HomuraCivAlpha64.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_HOMURA', 						48, 		'HomuraCivAlpha48.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_HOMURA', 						32, 		'HomuraCivAlpha32.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_HOMURA', 						24, 		'HomuraCivAlpha24.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_HOMURA', 						16, 		'HomuraCivAlpha16.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_SAYAKA', 						128, 		'SayakaIconAlpha128.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_SAYAKA', 						80, 		'SayakaIconAlpha80.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_SAYAKA', 						64, 		'SayakaIconAlpha64.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_SAYAKA', 						48, 		'SayakaIconAlpha48.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_SAYAKA', 						32, 		'SayakaIconAlpha32.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_SAYAKA', 						24, 		'SayakaIconAlpha24.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_SAYAKA', 						16, 		'SayakaIconAlpha16.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_KYOUKO', 						128, 		'KyoukoIconAlpha128.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_KYOUKO', 						80, 		'KyoukoIconAlpha80.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_KYOUKO', 						64, 		'KyoukoIconAlpha64.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_KYOUKO', 						48, 		'KyoukoIconAlpha48.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_KYOUKO', 						32, 		'KyoukoIconAlpha32.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_KYOUKO', 						24, 		'KyoukoIconAlpha24.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_KYOUKO', 						16, 		'KyoukoIconAlpha16.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_MAMI', 						128, 		'MamiIconAlpha128.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_MAMI', 						80, 		'MamiIconAlpha80.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_MAMI', 						64, 		'MamiIconAlpha64.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_MAMI', 						48, 		'MamiIconAlpha48.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_MAMI', 						32, 		'MamiIconAlpha32.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_MAMI', 						24, 		'MamiIconAlpha24.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_MAMI', 						16, 		'MamiIconAlpha16.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_NAGISA', 						128, 		'NagisaCivAlpha128.dds',			1, 				1),
			('CIV_ALPHA_ATLAS_NAGISA', 						80, 		'NagisaCivAlpha80.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_NAGISA', 						64, 		'NagisaCivAlpha64.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_NAGISA', 						48, 		'NagisaCivAlpha48.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_NAGISA', 						32, 		'NagisaCivAlpha32.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_NAGISA', 						24, 		'NagisaCivAlpha24.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_NAGISA', 						16, 		'NagisaCivAlpha16.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_ORIGINAL_MADOKA', 			128, 		'OriginalMadokaAlpha128.dds',		1, 				1),
			('CIV_ALPHA_ATLAS_ORIGINAL_MADOKA', 			80, 		'OriginalMadokaAlpha80.dds',		1, 				1),
			('CIV_ALPHA_ATLAS_ORIGINAL_MADOKA', 			64, 		'OriginalMadokaAlpha64.dds',		1, 				1),
			('CIV_ALPHA_ATLAS_ORIGINAL_MADOKA', 			48, 		'OriginalMadokaAlpha48.dds',		1, 				1),
			('CIV_ALPHA_ATLAS_ORIGINAL_MADOKA', 			32, 		'OriginalMadokaAlpha32.dds',		1, 				1),
			('CIV_ALPHA_ATLAS_ORIGINAL_MADOKA', 			24, 		'OriginalMadokaAlpha24.dds',		1, 				1),
			('CIV_ALPHA_ATLAS_ORIGINAL_MADOKA', 			16, 		'OriginalMadokaAlpha16.dds',		1, 				1),
			('CIV_ALPHA_ATLAS_KAORU_UMIKA', 				128, 		'PleiadesAlpha128.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_KAORU_UMIKA', 				80, 		'PleiadesAlpha80.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_KAORU_UMIKA', 				64, 		'PleiadesAlpha64.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_KAORU_UMIKA', 				48, 		'PleiadesAlpha48.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_KAORU_UMIKA', 				32, 		'PleiadesAlpha32.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_KAORU_UMIKA', 				24, 		'PleiadesAlpha24.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_KAORU_UMIKA', 				16, 		'PleiadesAlpha16.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_ORIKO_KIRIKA', 				128, 		'ShiromeAlpha128.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_ORIKO_KIRIKA', 				80, 		'ShiromeAlpha80.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_ORIKO_KIRIKA', 				64, 		'ShiromeAlpha64.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_ORIKO_KIRIKA', 				48, 		'ShiromeAlpha48.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_ORIKO_KIRIKA', 				32, 		'ShiromeAlpha32.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_ORIKO_KIRIKA', 				24, 		'ShiromeAlpha24.dds',				1, 				1),
			('CIV_ALPHA_ATLAS_ORIKO_KIRIKA', 				16, 		'ShiromeAlpha16.dds',				1, 				1),
			--------------------------Unit Flags-------------------------------------------------------------------------------
			('UNIT_ATLAS_PMMM_INCUBATOR', 					32, 		'UnitIncubatorAlpha.dds',			1, 				1),
			('PMMM_MAGICAL_GIRL_ALPHA_ATLAS', 				32, 		'MagicalGirlIcon32.dds',			1, 				1),
			('PMMM_WITCH_ALPHA_ATLAS', 						32, 		'WitchAlphaFlag.dds',				1, 				1),
			('PMMM_FAMILIAR_ALPHA_ATLAS', 					32, 		'FamiliarAlphaIcon.dds',			1, 				1),

			--------------------------Building Atlas------------------------------------------------------------------------
			('BUILDING_COLOR_ATLAS_PMMM_V21', 				256, 		'V21BuildingIconAtlas256.dds',		2, 				1),
			('BUILDING_COLOR_ATLAS_PMMM_V21', 				128, 		'V21BuildingIconAtlas128.dds',		2, 				1),
			('BUILDING_COLOR_ATLAS_PMMM_V21', 				80, 		'V21BuildingIconAtlas80.dds',		2, 				1),
			('BUILDING_COLOR_ATLAS_PMMM_V21', 				64, 		'V21BuildingIconAtlas64.dds',		2, 				1),
			('BUILDING_COLOR_ATLAS_PMMM_V21', 				45, 		'V21BuildingIconAtlas45.dds',		2, 				1),
			('BUILDING_COLOR_ATLAS_PMMM_V21', 				32, 		'V21BuildingIconAtlas32.dds',		2, 				1),

			('PMMM_ENTERTAINMENT_BUILDING_ATLAS', 			256, 		'PMMMEntertainmentAtlas256.dds',	8, 				2),
			('PMMM_ENTERTAINMENT_BUILDING_ATLAS', 			128, 		'PMMMEntertainmentAtlas128.dds',	8, 				2),
			('PMMM_ENTERTAINMENT_BUILDING_ATLAS', 			80, 		'PMMMEntertainmentAtlas80.dds',		8, 				2),
			('PMMM_ENTERTAINMENT_BUILDING_ATLAS', 			64, 		'PMMMEntertainmentAtlas64.dds',		8, 				2),
			('PMMM_ENTERTAINMENT_BUILDING_ATLAS', 			45, 		'PMMMEntertainmentAtlas45.dds',		8, 				2),
			('PMMM_ENTERTAINMENT_BUILDING_ATLAS', 			32, 		'PMMMEntertainmentAtlas32.dds',		8, 				2),

			--------------------------Improvement Atlas------------------------------------------------------------------------
			('BUILD_ATLAS_PMMM_FARSIGHT_ORACLE',			45,			'PMMMFarsightOracle45.dds',			1,				1),
			('BUILD_ATLAS_PMMM_FARSIGHT_ORACLE',			64,			'PMMMFarsightOracle64.dds',			1,				1),

			--------------------------Specialist Atlas-------------------------------------------------------------------------
			('SPECIALIST_ATLAS_PMMM',						256,		'PMMMEntertainerSpecialist256.dds',	1,				1),
			('SPECIALIST_ATLAS_PMMM',						128,		'PMMMEntertainerSpecialist128.dds',	1,				1),
			('SPECIALIST_ATLAS_PMMM',						64,			'PMMMEntertainerSpecialist64.dds',	1,				1),
			('SPECIALIST_ATLAS_PMMM',						32,			'PMMMEntertainerSpecialist32.dds',	1,				1),

			--------------------------Promotions Atlas------------------------------------------------------------------------
			('PROMOTION_ATLAS_PMMM_SOUL_GEMS',				32,			'SGPromotions32.dds',				5,				1),
			('PROMOTION_ATLAS_PMMM_SOUL_GEMS',				45,			'SGPromotions45.dds',				5,				1),
			('PROMOTION_ATLAS_PMMM_MOODS',					32,			'MoodPromotions32.dds',				5,				2),
			('PROMOTION_ATLAS_PMMM_V25_PROMOTIONS',			256,		'WFTWv25PromotionAtlas256.dds',		6,				1),
			('PROMOTION_ATLAS_PMMM_V25_PROMOTIONS',			32,			'WFTWv25PromotionAtlas32.dds',		6,				1),
			('PROMOTION_ATLAS_PMMM_V25_PROMOTIONS',			45,			'WFTWv25PromotionAtlas45.dds',		6,				1),
			('PROMOTION_ATLAS_PMMM_V25_PROMOTIONS',			64,			'WFTWv25PromotionAtlas64.dds',		6,				1),

			--------------------------Religion Atlas--------------------------------------------------------------------------
			('CHURCH_OF_MADOKA_ATLAS', 				128, 		'ChurchOfMadoka128.dds',	1, 				1),
			('CHURCH_OF_MADOKA_ATLAS', 				80, 		'ChurchOfMadoka80.dds',		1, 				1),
			('CHURCH_OF_MADOKA_ATLAS', 				64, 		'ChurchOfMadoka64.dds',		1, 				1),
			('CHURCH_OF_MADOKA_ATLAS', 				48, 		'ChurchOfMadoka48.dds',		1, 				1),
			('CHURCH_OF_MADOKA_ATLAS', 				32, 		'ChurchOfMadoka32.dds',		1, 				1),
			('CHURCH_OF_MADOKA_ATLAS', 				24, 		'ChurchOfMadoka24.dds',		1, 				1),
			('CHURCH_OF_MADOKA_ATLAS', 				16, 		'ChurchOfMadoka16.dds',		1, 				1),
			('CULT_OF_HOMURA_ATLAS', 				128, 		'CultOfHomura128.dds',		1, 				1),
			('CULT_OF_HOMURA_ATLAS', 				80, 		'CultOfHomura80.dds',		1, 				1),
			('CULT_OF_HOMURA_ATLAS', 				64, 		'CultOfHomura64.dds',		1, 				1),
			('CULT_OF_HOMURA_ATLAS', 				48, 		'CultOfHomura48.dds',		1, 				1),
			('CULT_OF_HOMURA_ATLAS', 				32, 		'CultOfHomura32.dds',		1, 				1),
			('CULT_OF_HOMURA_ATLAS', 				24, 		'CultOfHomura24.dds',		1, 				1),
			('CULT_OF_HOMURA_ATLAS', 				16, 		'CultOfHomura16.dds',		1, 				1),

			--------------------------MG Icon Overrides-----------------------------------------------------------------------
			('PMMM_LEADER_OVERRIDE_ATLAS',			256,		'PMMMLeaderOverride256.dds',3,				1),
			('PMMM_LEADER_OVERRIDE_ATLAS',			128,		'PMMMLeaderOverride128.dds',3,				1),
			('PMMM_LEADER_OVERRIDE_ATLAS',			64,			'PMMMLeaderOverride64.dds',	3,				1),

			--------------------------Mission Atlas---------------------------------------------------------------------------
			('PMMM_MISSION_ATLAS',					128,		'PMMMActionIcons128.dds',	8,				8),
			('PMMM_MISSION_ATLAS',					64,			'PMMMActionIcons64.dds',	8,				8),
			('PMMM_MISSION_ATLAS',					45,			'PMMMActionIcons45.dds',	8,				8),
			
			------------------------------------------------------------------------------------------------------------------
			------------------------MAGICAL GIRL ICON BUILDER-----------------------------------------------------------------
			------------------------------------------------------------------------------------------------------------------

			('MGIB_BODY_ATLAS',						256,		'MGIconBodyAtlas256.dds',	4,				1),
			('MGIB_BODY_ATLAS',						128,		'MGIconBodyAtlas128.dds',	4,				1),
			('MGIB_BODY_ATLAS',						64,			'MGIconBodyAtlas64.dds',	4,				1),

			('MGIB_OUTFIT1_ATLAS',					256,		'MGOutfit1Atlas256.dds',	4,				4),
			('MGIB_OUTFIT1_ATLAS',					128,		'MGOutfit1Atlas128.dds',	4,				4),
			('MGIB_OUTFIT1_ATLAS',					64,			'MGOutfit1Atlas64.dds',		4,				4),

			('MGIB_FACE1_ATLAS',					256,		'MGFace1Atlas256.dds',		4,				3),
			('MGIB_FACE1_ATLAS',					128,		'MGFace1Atlas128.dds',		4,				3),
			('MGIB_FACE1_ATLAS',					64,			'MGFace1Atlas64.dds',		4,				3),
			('MGIB_FACE1_ANGRY_ATLAS',				256,		'MGFace1AngryAtlas256.dds',	4,				3),
			('MGIB_FACE1_ANGRY_ATLAS',				128,		'MGFace1AngryAtlas128.dds',	4,				3),
			('MGIB_FACE1_ANGRY_ATLAS',				64,			'MGFace1AngryAtlas64.dds',	4,				3),
			('MGIB_FACE1_DEPRESSED_ATLAS',			256,		'MGFace1SadAtlas256.dds',	4,				3),
			('MGIB_FACE1_DEPRESSED_ATLAS',			128,		'MGFace1SadAtlas128.dds',	4,				3),
			('MGIB_FACE1_DEPRESSED_ATLAS',			64,			'MGFace1SadAtlas64.dds',	4,				3),
			('MGIB_FACE1_HAPPY_ATLAS',				256,		'MGFace1HappyAtlas256.dds',	4,				3),
			('MGIB_FACE1_HAPPY_ATLAS',				128,		'MGFace1HappyAtlas128.dds',	4,				3),
			('MGIB_FACE1_HAPPY_ATLAS',				64,			'MGFace1HappyAtlas64.dds',	4,				3),
			('MGIB_FACE1_JOYOUS_ATLAS',				256,		'MGFace1JoyousAtlas256.dds',4,				3),
			('MGIB_FACE1_JOYOUS_ATLAS',				128,		'MGFace1JoyousAtlas128.dds',4,				3),
			('MGIB_FACE1_JOYOUS_ATLAS',				64,			'MGFace1JoyousAtlas64.dds',	4,				3),

			('MGIB_HAIR1_ATLAS',					256,		'MGHair1Atlas256.dds',		4,				4),
			('MGIB_HAIR1_ATLAS',					128,		'MGHair1Atlas128.dds',		4,				4),
			('MGIB_HAIR1_ATLAS',					64,			'MGHair1Atlas64.dds',		4,				4),
			('MGIB_HAIR2_ATLAS',					256,		'MGHair2Atlas256.dds',		4,				4),
			('MGIB_HAIR2_ATLAS',					128,		'MGHair2Atlas128.dds',		4,				4),
			('MGIB_HAIR2_ATLAS',					64,			'MGHair2Atlas64.dds',		4,				4),
			('MGIB_HAIR3_ATLAS',					256,		'MGHair3Atlas256.dds',		4,				4),
			('MGIB_HAIR3_ATLAS',					128,		'MGHair3Atlas128.dds',		4,				4),
			('MGIB_HAIR3_ATLAS',					64,			'MGHair3Atlas64.dds',		4,				4),
			('MGIB_HAIR4_ATLAS',					256,		'MGHair4Atlas256.dds',		4,				4),
			('MGIB_HAIR4_ATLAS',					128,		'MGHair4Atlas128.dds',		4,				4),
			('MGIB_HAIR4_ATLAS',					64,			'MGHair4Atlas64.dds',		4,				4),
			('MGIB_HAIR5_ATLAS',					256,		'MGHair5Atlas256.dds',		4,				4),
			('MGIB_HAIR5_ATLAS',					128,		'MGHair5Atlas128.dds',		4,				4),
			('MGIB_HAIR5_ATLAS',					64,			'MGHair5Atlas64.dds',		4,				4),
			('MGIB_HAIR6_ATLAS',					256,		'MGHair6Atlas256.dds',		4,				4),
			('MGIB_HAIR6_ATLAS',					128,		'MGHair6Atlas128.dds',		4,				4),
			('MGIB_HAIR6_ATLAS',					64,			'MGHair6Atlas64.dds',		4,				4),
			
			('MGIB_ICONFA1_ATLAS',					256,		'MGAccessoryEyepatch256.dds',		4,				1),
			('MGIB_ICONFA1_ATLAS',					128,		'MGAccessoryEyepatch128.dds',		4,				1),
			('MGIB_ICONFA1_ATLAS',					64,			'MGAccessoryEyepatch64.dds',		4,				1),
			('MGIB_ICONHA1_ATLAS',					256,		'MGAccessoryTropicalFlowers256.dds',4,				1),
			('MGIB_ICONHA1_ATLAS',					128,		'MGAccessoryTropicalFlowers128.dds',4,				1),
			('MGIB_ICONHA1_ATLAS',					64,			'MGAccessoryTropicalFlowers64.dds',	4,				1),
			
			('PMMM_ICON_BUILDER_BACKGROUND_ATLAS',	256,	'MGIconBuilderBackground256.dds',1,			1),
			('PMMM_ICON_BUILDER_BACKGROUND_ATLAS',	128,	'MGIconBuilderBackground128.dds',1,			1),
			('PMMM_ICON_BUILDER_BACKGROUND_ATLAS',	64,		'MGIconBuilderBackground64.dds',1,			1);