/* INSERT INTO MG_RelationshipLevels
			(Type,								Description,									Tooltip,					
			MinValue,	MaxValue,		CannotIncrease,		CannotDecrease,		CombatStrengthBonus,	SoulGemModifier,	BonusHealing)
VALUES		
			--Unknown Relationship
			('MGRELATIONSHIP_NONE',				'TXT_KEY_PMMM_MGRELATIONSHIP_NONE',				'TXT_KEY_PMMM_MGRELATIONSHIP_NONE_TOOLTIP',
			0,			0,				0,					0,					0,						0,					0),

			--Positive Relationships
			('MGRELATIONSHIP_ACQUAINTANCES',	'TXT_KEY_PMMM_MGRELATIONSHIP_ACQUAINTANCES',	'TXT_KEY_PMMM_MGRELATIONSHIP_ACQUAINTANCES_TOOLTIP',
			1,			99,				0,					0,					0,						0,					0),
			('MGRELATIONSHIP_COMRADES',			'TXT_KEY_PMMM_MGRELATIONSHIP_COMRADES',			'TXT_KEY_PMMM_MGRELATIONSHIP_COMRADES_TOOLTIP',
			100,		299,			0,					0,					1,						0,					0),
			('MGRELATIONSHIP_FRIENDS',			'TXT_KEY_PMMM_MGRELATIONSHIP_FRIENDS',			'TXT_KEY_PMMM_MGRELATIONSHIP_FRIENDS_TOOLTIP',
			300,		699,			0,					0,					2,						-10,				0),
			('MGRELATIONSHIP_GOOD_FRIENDS',		'TXT_KEY_PMMM_MGRELATIONSHIP_GOOD_FRIENDS',		'TXT_KEY_PMMM_MGRELATIONSHIP_GOOD_FRIENDS_TOOLTIP',
			700,		1099,			0,					0,					2,						-10,				2),
			('MGRELATIONSHIP_TRUE_FRIENDS',		'TXT_KEY_PMMM_MGRELATIONSHIP_TRUE_FRIENDS',		'TXT_KEY_PMMM_MGRELATIONSHIP_TRUE_FRIENDS_TOOLTIP',
			1100,		1699,			0,					0,					3,						-15,				2),
			('MGRELATIONSHIP_BEST_FRIENDS',		'TXT_KEY_PMMM_MGRELATIONSHIP_BEST_FRIENDS',		'TXT_KEY_PMMM_MGRELATIONSHIP_BEST_FRIENDS_TOOLTIP',
			1700,		2499,			0,					1,					4,						-15,				2),
			('MGRELATIONSHIP_LOVE',				'TXT_KEY_PMMM_MGRELATIONSHIP_LOVE',				'TXT_KEY_PMMM_MGRELATIONSHIP_LOVE_TOOLTIP',
			2500,		3499,			0,					0,					5,						-25,				4),
			('MGRELATIONSHIP_FATED_COUPLE',		'TXT_KEY_PMMM_MGRELATIONSHIP_FATED_COUPLE',		'TXT_KEY_PMMM_MGRELATIONSHIP_FATED_COUPLE_TOOLTIP',
			3500,		9999,			1,					1,					5,						-25,				4),

			--Negative Relationships
			('MGRELATIONSHIP_MUTUAL_DISLIKE',	'TXT_KEY_PMMM_MGRELATIONSHIP_MUTUAL_DISLIKE',	'TXT_KEY_PMMM_MGRELATIONSHIP_MUTUAL_DISLIKE_TOOLTIP',
			-1,			-99,			0,					0,					0,						0,					0),
			('MGRELATIONSHIP_ENEMIES',			'TXT_KEY_PMMM_MGRELATIONSHIP_ENEMIES',			'TXT_KEY_PMMM_MGRELATIONSHIP_ENEMIES_TOOLTIP',
			-100,		-299,			0,					0,					-1,						10,					0),
			('MGRELATIONSHIP_HATE',				'TXT_KEY_PMMM_MGRELATIONSHIP_HATE',				'TXT_KEY_PMMM_MGRELATIONSHIP_HATE_TOOLTIP',
			-300,		-999,			0,					0,					-3,						15,					0),
			('MGRELATIONSHIP_MORTAL_ENEMIES',	'TXT_KEY_PMMM_MGRELATIONSHIP_MORTAL_ENEMIES',	'TXT_KEY_PMMM_MGRELATIONSHIP_MORTAL_ENEMIES_TOOLTIP',
			-1000,		-9999,			1,					1,					-5,						25,					0); */