INSERT INTO Concepts
			(Type,									Topic,					Description,										Summary,
			AdvisorQuestion,										Advisor,		CivilopediaHeaderType)
VALUES		--Magical Girl Header
			('CONCEPT_PMMM_EARNING_MAGICAL_GIRLS',	'TXT_KEY_PMMM_WFTW',	'TXT_KEY_PMMM_CONCEPT_EARNING_MAGICAL_GIRLS_TITLE', 'TXT_KEY_PMMM_CONCEPT_EARNING_MAGICAL_GIRLS_TEXT',
			'TXT_KEY_PMMM_CONCEPT_EARNING_MAGICAL_GIRLS_ADV_QUEST',	'MILITARY',		'HEADER_PMMM_WFTW'),
			('CONCEPT_PMMM_SOUL_GEMS',				'TXT_KEY_PMMM_WFTW',	'TXT_KEY_PMMM_CONCEPT_SOUL_GEMS_TITLE',				'TXT_KEY_PMMM_CONCEPT_SOUL_GEMS_TEXT',
			'TXT_KEY_PMMM_CONCEPT_SOUL_GEMS_ADV_QUEST',				'MILITARY',		'HEADER_PMMM_WFTW'),
			('CONCEPT_PMMM_MOODS',				'TXT_KEY_PMMM_WFTW',	'TXT_KEY_PMMM_CONCEPT_MOODS_TITLE',				'TXT_KEY_PMMM_CONCEPT_MOODS_TEXT',
			'TXT_KEY_PMMM_CONCEPT_MOODS_ADV_QUEST',				'MILITARY',		'HEADER_PMMM_WFTW'),

			--Witch Header
			('CONCEPT_PMMM_WITCHES',				'TXT_KEY_PMMM_WFTW',	'TXT_KEY_PMMM_CONCEPT_WITCHES_TITLE',				'TXT_KEY_PMMM_CONCEPT_WITCHES_TEXT',
			'TXT_KEY_PMMM_CONCEPT_WITCHES_ADV_QUEST',				'MILITARY',		'HEADER_PMMM_WFTW'),
			('CONCEPT_PMMM_FAMILIARS',				'TXT_KEY_PMMM_WFTW',	'TXT_KEY_PMMM_CONCEPT_FAMILIARS_TITLE',				'TXT_KEY_PMMM_CONCEPT_FAMILIARS_TEXT',
			'TXT_KEY_PMMM_CONCEPT_FAMILIARS_ADV_QUEST',				'MILITARY',		'HEADER_PMMM_WFTW'),
			('CONCEPT_PMMM_WITCH_BARRIERS',			'TXT_KEY_PMMM_WFTW',	'TXT_KEY_PMMM_CONCEPT_WITCH_BARRIERS_TITLE',		'TXT_KEY_PMMM_CONCEPT_WITCH_BARRIERS_TEXT',
			'TXT_KEY_PMMM_CONCEPT_WITCH_BARRIERS_ADV_QUEST',				'MILITARY',		'HEADER_PMMM_WFTW'),
			('CONCEPT_PMMM_HIDDEN_WITCH_BARRIERS',	'TXT_KEY_PMMM_WFTW',	'TXT_KEY_PMMM_CONCEPT_HIDDEN_WITCH_BARRIERS_TITLE',	'TXT_KEY_PMMM_CONCEPT_HIDDEN_WITCH_BARRIERS_TEXT',
			'TXT_KEY_PMMM_CONCEPT_HIDDEN_WITCH_BARRIERS_ADV_QUEST',	'MILITARY',		'HEADER_PMMM_WFTW');