local iMaxCivs = GameDefines.MAX_MAJOR_CIVS

--Civ Identifiers
--Hyperdimension
local iNoire = GameInfoTypes.LEADER_VV_NOIRE or -1
local iBlackHeart = GameInfoTypes.LEADER_VV_BLACK_HEART or -1
local iNoireCiv = GameInfoTypes.CIVILIZATION_VV_LASTATION or -1
local iBlackHeartCiv = GameInfoTypes.CIVILIZATION_VV_LASTATION_BH or -1
--Ultradimension
local iNoireUltra = GameInfoTypes.LEADER_VV_NOIRE_ULTRA or -1
local iBlackHeartUltra = GameInfoTypes.LEADER_VV_BLACK_HEART_ULTRA or -1
local iNoireCivUltra = GameInfoTypes.CIVILIZATION_VV_LASTATION_ULTRA or -1
local iBlackHeartCivUltra = GameInfoTypes.CIVILIZATION_VV_LASTATION_BH_ULTRA or -1

local tNoires = {}
local tHDNoires = {}
local tUDNoires = {}
for i = 0, iMaxCivs - 1, 1 do
	local pPlayer = Players[i]
	if pPlayer:IsEverAlive() then
		local iLeaderType = pPlayer:GetLeaderType()
		if (iLeaderType == iNoire or iLeaderType == iBlackHeart) then
			tNoires[i] = true
			tHDNoires[i] = true
		elseif (iLeaderType == iNoireUltra or iLeaderType == iBlackHeartUltra) then
			tNoires[i] = true
			tUDNoires[i] = true
		end
	end
end



---------------------------------------------------------------------------------------------------------------------------------------------------------
-- FLUFF
---------------------------------------------------------------------------------------------------------------------------------------------------------

--Unique Dialog Text for specific leaders.


local tNeptuneCivs = {
	["CIVILIZATION_PLANEPTUNE"] = true,
	["CIVILIZATION_VV_PLANEPTUNE"] = true,
	["CIVILIZATION_VV_PLANEPTUNE_PH"] = true
}

local tNepgearCivs = {
	["CIVILIZATION_VV_PLANEPTUNE_NG"] = true,
	["CIVILIZATION_VV_PLANEPTUNE_PS"] = true
}

local tPlutiaCivs = {
	["CIVILIZATION_VV_PLANEPTUNE_PL"] = true,
	["CIVILIZATION_VV_PLANEPTUNE_IH"] = true
}

local tNoireCivs = {
	["CIVILIZATION_LASTATION"] = true,
	["CIVILIZATION_VV_LASTATION"] = true,
	["CIVILIZATION_VV_LASTATION_BH"] = true,
	["CIVILIZATION_VV_LASTATION_ULTRA"] = true,
	["CIVILIZATION_VV_LASTATION_BH_ULTRA"] = true
}

local tHDNoireCivs = {
	["CIVILIZATION_LASTATION"] = true,
	["CIVILIZATION_VV_LASTATION"] = true,
	["CIVILIZATION_VV_LASTATION_BH"] = true
}

local tUDNoireCivs = {
	["CIVILIZATION_VV_LASTATION_ULTRA"] = true,
	["CIVILIZATION_VV_LASTATION_BH_ULTRA"] = true
}

local tUniCivs = {
	["CIVILIZATION_VV_LASTATION_UN"] = true,
	["CIVILIZATION_VV_LASTATION_BS"] = true
}

local tVertCivs = {
	["CIVILIZATION_LEANBOX"] = true,
	["CIVILIZATION_VV_LEANBOX"] = true,
	["CIVILIZATION_VV_LEANBOX_GH"] = true,
	["CIVILIZATION_VV_LEANBOX_ULTRA"] = true,
	["CIVILIZATION_VV_LEANBOX_GH_ULTRA"] = true
}

local tBlancCivs = {
	["CIVILIZATION_LOWEE"] = true,
	["CIVILIZATION_VV_LOWEE"] = true,
	["CIVILIZATION_VV_LOWEE_WH"] = true,
	["CIVILIZATION_VV_LOWEE_ULTRA"] = true,
	["CIVILIZATION_VV_LOWEE_WH_ULTRA"] = true
}


include("UniqueDiplomacyUtilsV3.lua")
function ChangeDiplomacyReference(targetReference, newReference)
	--print("Currently changing " .. targetReference .. " to " .. newReference .. "...");
	-- We can't always assume that the references exist, so therefore we need to check if they do first
	
	-- Vice: Commented this part out for speed, since the references will always exist when iterating over GameInfo.Diplomacy_Responses.
	-- local reference;
	-- for _ in DB.Query("SELECT Response FROM Diplomacy_Responses WHERE Response= '" .. targetReference .. "'") do reference = _.Response end
	
	if targetReference then
		--print(targetReference .. " exists; now changing it to the new reference...");
		local locale = "Language_" ..Locale.GetCurrentLanguage().Type;
		--print("Current locale is " .. locale .. ".");
		local text;

		--print("Querying with: SELECT Text FROM " ..locale .." WHERE Tag LIKE '" ..newReference.."'");
		for _ in DB.Query("SELECT Text FROM " ..locale .." WHERE Tag LIKE '" ..newReference.."'") do text = _.Text end
		if text then
			for _ in DB.Query("UPDATE Diplomacy_Responses SET Response = '" .. newReference .. "' WHERE Response='" .. targetReference .. "'") do end
			--print("Reference change complete!");
		else
			--print(newReference .. " does not refer to any new lines in this locale, therefore we won't replace it.");		
		end
	else
		--print(targetReference .. " doesn't exist therefore we cannot replace it with a new reference.");
	end
end


function NoireCharacterSpecificDialogText()
	local locale = "Language_" ..Locale.GetCurrentLanguage().Type;
	local pActivePlayer = Players[Game:GetActivePlayer()]
	local sCivilizationType = GameInfo.Civilizations[pActivePlayer:GetCivilizationType()].Type

	
	if tNeptuneCivs[sCivilizationType] then
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_DEFEATED%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_FIRSTGREETING%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDNOIRE_DEFEATED%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDNOIRE_FIRSTGREETING%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_POLITE_HELLO%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_NEUTRAL_HELLO%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_HOSTILE_HELLO%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_GREETING_HOSTILE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_ATTACKED_HOSTILE%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_WAR_DECLARED_ON%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_HOSTILE%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_WAR_DECLARED_ON%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_HOSTILE%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_WAR_DECLARED_ON%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_ATTACKED_EXCITED%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_WAR_DECLARED_ON%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_EXCITED%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_WAR_DECLARED_ON%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_EXCITED%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_WAR_DECLARED_ON%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_DOW_LAND%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_DECLARES_WAR%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_DOW_GENERIC%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_DECLARES_WAR%")

		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDBLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDBLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_POLITE_HELLO%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_NEUTRAL_HELLO%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_HOSTILE_HELLO%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_GREETING_HOSTILE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_ATTACKED_HOSTILE%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_WAR_DECLARED_ON%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_ATTACKED_WEAK_HOSTILE%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_WAR_DECLARED_ON%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_ATTACKED_STRONG_HOSTILE%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_WAR_DECLARED_ON%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_ATTACKED_EXCITED%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_WAR_DECLARED_ON%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_ATTACKED_WEAK_EXCITED%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_WAR_DECLARED_ON%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_ATTACKED_STRONG_EXCITED%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_WAR_DECLARED_ON%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_DOW_LAND%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_DECLARES_WAR%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_DOW_GENERIC%", "TXT_KEY_UD_VS_NEPTUNE_NOIRE_DECLARES_WAR%")
	elseif tNoireCivs[sCivilizationType] then
		if tHDNoireCivs[sCivilizationType] then
			ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDNOIRE_DEFEATED%", "TXT_KEY_UD_VS_HDNOIRE_UDNOIRE_DEFEATED%")
			ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDNOIRE_FIRSTGREETING%", "TXT_KEY_UD_VS_HDNOIRE_UDNOIRE_FIRSTGREETING%")
			ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_HOSTILE_HELLO%", "TXT_KEY_UD_VS_HDNOIRE_UDNOIRE_GREETING_HOSTILE%")

			ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDBLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_HDNOIRE_UDNOIRE_DEFEATED%")
			ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDBLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_HDNOIRE_UDNOIRE_FIRSTGREETING%")
			ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_HOSTILE_HELLO%", "TXT_KEY_UD_VS_HDNOIRE_UDNOIRE_GREETING_HOSTILE%")
		else
			ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_DEFEATED%", "TXT_KEY_UD_VS_UDNOIRE_HDNOIRE_DEFEATED%")
			ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_FIRSTGREETING%", "TXT_KEY_UD_VS_UDNOIRE_HDNOIRE_FIRSTGREETING%")
			ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_HOSTILE_HELLO%", "TXT_KEY_UD_VS_UDNOIRE_HDNOIRE_GREETING_HOSTILE%")

			ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_UDNOIRE_HDNOIRE_DEFEATED%")
			ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_UDNOIRE_HDNOIRE_FIRSTGREETING%")
			ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_HOSTILE_HELLO%", "TXT_KEY_UD_VS_UDNOIRE_HDNOIRE_GREETING_HOSTILE%")
		end
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_POLITE_HELLO%", "TXT_KEY_UD_VS_NOIRE_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_NEUTRAL_HELLO%", "TXT_KEY_UD_VS_NOIRE_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_ATTACKED_HOSTILE%", "TXT_KEY_UD_VS_NOIRE_NOIRE_WAR_DECLARATION%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_HOSTILE%", "TXT_KEY_UD_VS_NOIRE_NOIRE_WAR_DECLARATION%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_HOSTILE%", "TXT_KEY_UD_VS_NOIRE_NOIRE_WAR_DECLARATION%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_ATTACKED_EXCITED%", "TXT_KEY_UD_VS_NOIRE_NOIRE_WAR_DECLARATION%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_EXCITED%", "TXT_KEY_UD_VS_NOIRE_NOIRE_WAR_DECLARATION%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_EXCITED%", "TXT_KEY_UD_VS_NOIRE_NOIRE_WAR_DECLARATION%")

		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_NOIRE_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_NOIRE_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_POLITE_HELLO%", "TXT_KEY_UD_VS_NOIRE_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_NEUTRAL_HELLO%", "TXT_KEY_UD_VS_NOIRE_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_ATTACKED_HOSTILE%", "TXT_KEY_UD_VS_NOIRE_NOIRE_WAR_DECLARATION%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_ATTACKED_WEAK_HOSTILE%", "TXT_KEY_UD_VS_NOIRE_NOIRE_WAR_DECLARATION%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_ATTACKED_STRONG_HOSTILE%", "TXT_KEY_UD_VS_NOIRE_NOIRE_WAR_DECLARATION%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_ATTACKED_EXCITED%", "TXT_KEY_UD_VS_NOIRE_NOIRE_WAR_DECLARATION%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_ATTACKED_WEAK_EXCITED%", "TXT_KEY_UD_VS_NOIRE_NOIRE_WAR_DECLARATION%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_ATTACKED_STRONG_EXCITED%", "TXT_KEY_UD_VS_NOIRE_NOIRE_WAR_DECLARATION%")
	elseif tNepgearCivs[sCivilizationType] then
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_DEFEATED%", "TXT_KEY_UD_VS_NEPGEAR_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_FIRSTGREETING%", "TXT_KEY_UD_VS_NEPGEAR_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDNOIRE_DEFEATED%", "TXT_KEY_UD_VS_NEPGEAR_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDNOIRE_FIRSTGREETING%", "TXT_KEY_UD_VS_NEPGEAR_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_POLITE_HELLO%", "TXT_KEY_UD_VS_NEPGEAR_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_NEUTRAL_HELLO%", "TXT_KEY_UD_VS_NEPGEAR_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_HOSTILE_HELLO%", "TXT_KEY_UD_VS_NEPGEAR_NOIRE_GREETING_HOSTILE%")

		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_NEPGEAR_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_NEPGEAR_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDBLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_NEPGEAR_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDBLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_NEPGEAR_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_POLITE_HELLO%", "TXT_KEY_UD_VS_NEPGEAR_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_NEUTRAL_HELLO%", "TXT_KEY_UD_VS_NEPGEAR_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_HOSTILE_HELLO%", "TXT_KEY_UD_VS_NEPGEAR_NOIRE_GREETING_HOSTILE%")
	elseif tPlutiaCivs[sCivilizationType] then
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_DEFEATED%", "TXT_KEY_UD_VS_PLUTIA_HDNOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_FIRSTGREETING%", "TXT_KEY_UD_VS_PLUTIA_HDNOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDNOIRE_DEFEATED%", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDNOIRE_FIRSTGREETING%", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_FIRSTGREETING%")
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_GREETING_POLITE_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_POLITE_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_GREETING_NEUTRAL_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_NEUTRAL_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_GREETING_HOSTILE_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_HOSTILE_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_WEAK_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_STRONG_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_WEAK_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_STRONG_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_LAND", "TXT_KEY_LEADER_VV_NOIRE_DOW_LAND%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_GENERIC", "TXT_KEY_LEADER_VV_NOIRE_DOW_GENERIC%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_GREETING_POLITE_HELLO", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_GREETING_POLITE%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_GREETING_NEUTRAL_HELLO", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_GREETING_POLITE%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_GREETING_HOSTILE_HELLO", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_GREETING_HOSTILE%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_EXCITED", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_WEAK_EXCITED", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_STRONG_EXCITED", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_HOSTILE", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_WEAK_HOSTILE", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_STRONG_HOSTILE", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_LAND", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_WORLD_CONQUEST", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_OPPORTUNITY", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_DESPERATE", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_BETRAYAL", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_WEAK_BETRAYAL", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_REGRET", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARATION%", 100)

		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_PLUTIA_HDNOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_PLUTIA_HDNOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDBLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDBLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_FIRSTGREETING%")
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_GREETING_POLITE_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_POLITE_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_GREETING_NEUTRAL_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_NEUTRAL_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_GREETING_HOSTILE_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_HOSTILE_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_WEAK_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_STRONG_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_WEAK_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_STRONG_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_LAND", "TXT_KEY_LEADER_VV_NOIRE_DOW_LAND%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_GENERIC", "TXT_KEY_LEADER_VV_NOIRE_DOW_GENERIC%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_GREETING_POLITE_HELLO", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_GREETING_POLITE%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_GREETING_NEUTRAL_HELLO", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_GREETING_POLITE%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_GREETING_HOSTILE_HELLO", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_GREETING_HOSTILE%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_EXCITED", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_WEAK_EXCITED", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_STRONG_EXCITED", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_HOSTILE", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_WEAK_HOSTILE", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_STRONG_HOSTILE", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_LAND", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_WORLD_CONQUEST", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_OPPORTUNITY", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_DESPERATE", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_BETRAYAL", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_WEAK_BETRAYAL", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_REGRET", "TXT_KEY_UD_VS_PLUTIA_UDNOIRE_WAR_DECLARATION%", 100)
	elseif tUniCivs[sCivilizationType] then
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_DEFEATED%", "TXT_KEY_UD_VS_UNI_HDNOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_FIRSTGREETING%", "TXT_KEY_UD_VS_UNI_HDNOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_GREETING_WORKING_WITH%", "TXT_KEY_UD_VS_UNI_HDNOIRE_FRIEND_GREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_DEC_FRIENDSHIP%", "TXT_KEY_UD_VS_UNI_HDNOIRE_FRIENDSHIP%")
		RemoveDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_GREETING_POLITE_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_POLITE_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_GREETING_NEUTRAL_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_NEUTRAL_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_GREETING_HOSTILE_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_HOSTILE_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_ATTACKED_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_ATTACKED_WEAK_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_ATTACKED_STRONG_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_ATTACKED_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_ATTACKED_WEAK_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_ATTACKED_STRONG_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_DOW_LAND", "TXT_KEY_LEADER_VV_NOIRE_DOW_LAND%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_DOW_GENERIC", "TXT_KEY_LEADER_VV_NOIRE_DOW_GENERIC%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_GREETING_POLITE_HELLO", "TXT_KEY_UD_VS_UNI_HDNOIRE_GREETING_POLITE%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_GREETING_NEUTRAL_HELLO", "TXT_KEY_UD_VS_UNI_HDNOIRE_GREETING_POLITE%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_GREETING_HOSTILE_HELLO", "TXT_KEY_UD_VS_UNI_HDNOIRE_GREETING_HOSTILE%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_ATTACKED_EXCITED", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_ATTACKED_WEAK_EXCITED", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_ATTACKED_STRONG_EXCITED", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_ATTACKED_HOSTILE", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_ATTACKED_WEAK_HOSTILE", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_ATTACKED_STRONG_HOSTILE", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_DOW_LAND", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_DOW_WORLD_CONQUEST", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_DOW_OPPORTUNITY", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_DOW_DESPERATE", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_DOW_BETRAYAL", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_DOW_WEAK_BETRAYAL", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE", "RESPONSE_DOW_REGRET", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARATION%", 100)

		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_UNI_HDNOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_UNI_HDNOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_GREETING_WORKING_WITH%", "TXT_KEY_UD_VS_UNI_HDNOIRE_FRIEND_GREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_DEC_FRIENDSHIP%", "TXT_KEY_UD_VS_UNI_HDNOIRE_FRIENDSHIP%")
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_GREETING_POLITE_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_POLITE_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_GREETING_NEUTRAL_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_NEUTRAL_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_GREETING_HOSTILE_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_HOSTILE_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_ATTACKED_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_ATTACKED_WEAK_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_ATTACKED_STRONG_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_ATTACKED_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_ATTACKED_WEAK_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_ATTACKED_STRONG_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_DOW_LAND", "TXT_KEY_LEADER_VV_NOIRE_DOW_LAND%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_DOW_GENERIC", "TXT_KEY_LEADER_VV_NOIRE_DOW_GENERIC%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_GREETING_POLITE_HELLO", "TXT_KEY_UD_VS_UNI_HDNOIRE_GREETING_POLITE%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_GREETING_NEUTRAL_HELLO", "TXT_KEY_UD_VS_UNI_HDNOIRE_GREETING_POLITE%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_GREETING_HOSTILE_HELLO", "TXT_KEY_UD_VS_UNI_HDNOIRE_GREETING_HOSTILE%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_ATTACKED_EXCITED", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_ATTACKED_WEAK_EXCITED", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_ATTACKED_STRONG_EXCITED", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_ATTACKED_HOSTILE", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_ATTACKED_WEAK_HOSTILE", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_ATTACKED_STRONG_HOSTILE", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_DOW_LAND", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_DOW_WORLD_CONQUEST", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_DOW_OPPORTUNITY", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_DOW_DESPERATE", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_DOW_BETRAYAL", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_DOW_WEAK_BETRAYAL", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART", "RESPONSE_DOW_REGRET", "TXT_KEY_UD_VS_UNI_HDNOIRE_WAR_DECLARATION%", 100)
		
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDNOIRE_DEFEATED%", "TXT_KEY_UD_VS_UNI_UDNOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDNOIRE_FIRSTGREETING%", "TXT_KEY_UD_VS_UNI_UDNOIRE_FIRSTGREETING%")
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_GREETING_POLITE_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_POLITE_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_GREETING_NEUTRAL_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_NEUTRAL_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_GREETING_HOSTILE_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_HOSTILE_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_WEAK_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_STRONG_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_WEAK_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_STRONG_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_LAND", "TXT_KEY_LEADER_VV_NOIRE_DOW_LAND%", 100)
		RemoveDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_GENERIC", "TXT_KEY_LEADER_VV_NOIRE_DOW_GENERIC%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_GREETING_POLITE_HELLO", "TXT_KEY_UD_VS_UNI_UDNOIRE_GREETING_POLITE%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_GREETING_NEUTRAL_HELLO", "TXT_KEY_UD_VS_UNI_UDNOIRE_GREETING_POLITE%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_GREETING_HOSTILE_HELLO", "TXT_KEY_UD_VS_UNI_UDNOIRE_GREETING_HOSTILE%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_EXCITED", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_WEAK_EXCITED", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_STRONG_EXCITED", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_HOSTILE", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_WEAK_HOSTILE", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_ATTACKED_STRONG_HOSTILE", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_LAND", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_WORLD_CONQUEST", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_OPPORTUNITY", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_DESPERATE", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_BETRAYAL", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_WEAK_BETRAYAL", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_NOIRE_ULTRA", "RESPONSE_DOW_REGRET", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARATION%", 100)

		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDBLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_UNI_UDNOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDBLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_UNI_UDNOIRE_FIRSTGREETING%")
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_GREETING_POLITE_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_POLITE_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_GREETING_NEUTRAL_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_NEUTRAL_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_GREETING_HOSTILE_HELLO", "TXT_KEY_LEADER_VV_NOIRE_GREETING_HOSTILE_HELLO%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_WEAK_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_STRONG_EXCITED", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_EXCITED%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_WEAK_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_WEAK_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_STRONG_HOSTILE", "TXT_KEY_LEADER_VV_NOIRE_ATTACKED_STRONG_HOSTILE%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_LAND", "TXT_KEY_LEADER_VV_NOIRE_DOW_LAND%", 100)
		RemoveDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_GENERIC", "TXT_KEY_LEADER_VV_NOIRE_DOW_GENERIC%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_GREETING_POLITE_HELLO", "TXT_KEY_UD_VS_UNI_UDNOIRE_GREETING_POLITE%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_GREETING_NEUTRAL_HELLO", "TXT_KEY_UD_VS_UNI_UDNOIRE_GREETING_POLITE%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_GREETING_HOSTILE_HELLO", "TXT_KEY_UD_VS_UNI_UDNOIRE_GREETING_HOSTILE%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_EXCITED", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_WEAK_EXCITED", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_STRONG_EXCITED", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_HOSTILE", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_WEAK_HOSTILE", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_ATTACKED_STRONG_HOSTILE", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARED_ON%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_LAND", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_WORLD_CONQUEST", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_OPPORTUNITY", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_DESPERATE", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_BETRAYAL", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_WEAK_BETRAYAL", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARATION%", 100)
		AddDiplomacyResponse("LEADER_VV_BLACK_HEART_ULTRA", "RESPONSE_DOW_REGRET", "TXT_KEY_UD_VS_UNI_UDNOIRE_WAR_DECLARATION%", 100)
	elseif tBlancCivs[sCivilizationType] then
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_DEFEATED%", "TXT_KEY_UD_VS_BLANC_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_FIRSTGREETING%", "TXT_KEY_UD_VS_BLANC_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDNOIRE_DEFEATED%", "TXT_KEY_UD_VS_BLANC_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDNOIRE_FIRSTGREETING%", "TXT_KEY_UD_VS_BLANC_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_POLITE_HELLO%", "TXT_KEY_UD_VS_BLANC_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_NEUTRAL_HELLO%", "TXT_KEY_UD_VS_BLANC_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_HOSTILE_HELLO%", "TXT_KEY_UD_VS_BLANC_NOIRE_GREETING_HOSTILE%")

		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_BLANC_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_BLANC_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDBLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_BLANC_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDBLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_BLANC_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_POLITE_HELLO%", "TXT_KEY_UD_VS_BLANC_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_NEUTRAL_HELLO%", "TXT_KEY_UD_VS_BLANC_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_HOSTILE_HELLO%", "TXT_KEY_UD_VS_BLANC_NOIRE_GREETING_HOSTILE%")
	elseif tVertCivs[sCivilizationType] then
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_DEFEATED%", "TXT_KEY_UD_VS_VERT_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDNOIRE_FIRSTGREETING%", "TXT_KEY_UD_VS_VERT_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDNOIRE_DEFEATED%", "TXT_KEY_UD_VS_VERT_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDNOIRE_FIRSTGREETING%", "TXT_KEY_UD_VS_VERT_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_POLITE_HELLO%", "TXT_KEY_UD_VS_VERT_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_NEUTRAL_HELLO%", "TXT_KEY_UD_VS_VERT_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_NOIRE_GREETING_HOSTILE_HELLO%", "TXT_KEY_UD_VS_VERT_NOIRE_GREETING_HOSTILE%")

		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_VERT_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_HDBLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_VERT_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDBLACK_HEART_DEFEATED%", "TXT_KEY_UD_VS_VERT_NOIRE_DEFEATED%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_UDBLACK_HEART_FIRSTGREETING%", "TXT_KEY_UD_VS_VERT_NOIRE_FIRSTGREETING%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_POLITE_HELLO%", "TXT_KEY_UD_VS_VERT_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_NEUTRAL_HELLO%", "TXT_KEY_UD_VS_VERT_NOIRE_GREETING_POLITE%")
		ChangeDiplomacyReference("TXT_KEY_LEADER_VV_BLACK_HEART_GREETING_HOSTILE_HELLO%", "TXT_KEY_UD_VS_VERT_NOIRE_GREETING_HOSTILE%")
	end
end


--If both Noires are in the game, UD Noire's description is changed to differentiate.
function UpdateNoireCivDescriptions()
	local bIsHDNoire
	local bIsUDNoire
	for i = 0, iMaxCivs - 1, 1 do
		local pPlayer = Players[i]
		if pPlayer:IsEverAlive() then
			local iUDNoirePlayer;
			local sCivilizationType = GameInfo.Civilizations[pPlayer:GetCivilizationType()].Type
			if sCivilizationType == "CIVILIZATION_VV_LASTATION" or sCivilizationType == "CIVILIZATION_VV_LASTATION_BH" then
				bIsHDNoire = true
			elseif sCivilizationType == "CIVILIZATION_VV_LASTATION_ULTRA" or sCivilizationType == "CIVILIZATION_VV_LASTATION_BH_ULTRA" then
				bIsUDNoire = true
				iUDNoirePlayer = i
			end
			if bIsHDNoire and bIsUDNoire then
				if iUDNoirePlayer then
					local pUD = Players[iUDNoirePlayer]
					if pUD:GetCivilizationShortDescription() == Locale.ConvertTextKey("TXT_KEY_CIV_VV_LASTATION_SHORT_DESC") then
						PreGame.SetCivilizationShortDescription(iUDNoirePlayer, "TXT_KEY_CIV_VV_LASTATION_ULTRA_SHORT_DESC_ALT")
					end
					if pUD:GetCivilizationDescription() == Locale.ConvertTextKey("TXT_KEY_CIV_VV_LASTATION_DESC") then
						PreGame.SetCivilizationDescription(iUDNoirePlayer, "TXT_KEY_CIV_VV_LASTATION_ULTRA_DESC_ALT")
					end
					if pUD:GetCivilizationAdjective() == Locale.ConvertTextKey("TXT_KEY_CIV_VV_LASTATION_ADJECTIVE") then
						PreGame.SetCivilizationAdjective(iUDNoirePlayer, "TXT_KEY_CIV_VV_LASTATION_ULTRA_ADJECTIVE_ALT")
					end
				end
				ChangeDiplomacyGameText("TXT_KEY_CIV_VV_LASTATION_ULTRA_DESC", "TXT_KEY_CIV_VV_LASTATION_ULTRA_DESC_ALT")
				ChangeDiplomacyGameText("TXT_KEY_CIV_VV_LASTATION_ULTRA_SHORT_DESC", "TXT_KEY_CIV_VV_LASTATION_ULTRA_SHORT_DESC_ALT")
				ChangeDiplomacyGameText("TXT_KEY_CIV_VV_LASTATION_ULTRA_ADJECTIVE", "TXT_KEY_CIV_VV_LASTATION_ULTRA_ADJECTIVE_ALT")
				ChangeDiplomacyGameText("TXT_KEY_CITY_NAME_VV_HDNCAPITAL_LASTATION_ULTRA", "TXT_KEY_CITY_NAME_VV_HDNCAPITAL_LASTATION_ULTRA_ALT")
				Locale.SetCurrentLanguage(Locale.GetCurrentLanguage().Type)
				break
			end
		end
	end
end

function OnLoadScreenCloseNoireText()
	NoireCharacterSpecificDialogText()
	-- if not HDNMod.NoireTextInit then
		UpdateNoireCivDescriptions()
		-- HDNMod.NoireTextInit = true
	-- end
end

Events.LoadScreenClose.Add(OnLoadScreenCloseNoireText)


--If a city is founded with the name "Lastation", add a numeral after it for each other one in the world. Lastation, Lastation 2, Lastation 3, etc.
function LastationNumeralNaming(iPlotX, iPlotY, iOldPop, iNewPop)
	if iOldPop == 0 then
		local pPlot = Map.GetPlot(iPlotX, iPlotY)
		local pCity = pPlot:GetPlotCity()
		if pCity then
			local pPlayer = Players[pCity:GetOwner()]
			if pPlayer:GetNumCities() == 1 then
				local sCivilizationType = GameInfo.Civilizations[pPlayer:GetCivilizationType()].Type
				if string.find(sCivilizationType, "LASTATION") then
					local sName = Locale.ConvertTextKey("TXT_KEY_CITY_NAME_VV_HDNCAPITAL_LASTATION")
					local iNumber = 1
					for i = 0, GameDefines.MAX_CIV_PLAYERS, 1 do
						for pLoopCity in Players[i]:Cities() do
							if string.find(pLoopCity:GetName(), sName) and pCity ~= pLoopCity then
								iNumber = iNumber + 1
							end
						end
					end
					if iNumber > 1 then
						sName = sName.." "..tostring(iNumber)
					end
					print(sName)
					pCity:SetName(sName)
				end
			end
		end
	end
end
GameEvents.SetPopulation.Add(LastationNumeralNaming)


--Special Leaderscene logic for UD Noire:
--If the player is Iris and she is not Hostile, Denouncing, or at War, she is pretty terrified.
local iIrisHeart = GameInfoTypes.LEADER_VV_IRIS_HEART
function NoireSpecialLeaderscene( iPlayer, iDiploUIState, szLeaderMessage, iAnimationAction, iData1 )
	local pPlayer = Players[iPlayer]
	local pActivePlayer = Players[Game:GetActivePlayer()]
	if pPlayer:GetLeaderType() == iNoireUltra and pActivePlayer:GetLeaderType() == iIrisHeart
	and not pPlayer:IsDenouncingPlayer(Game:GetActivePlayer()) and not Teams[pPlayer:GetTeam()]:IsAtWar(pActivePlayer:GetTeam()) then
		local iApproach = pActivePlayer:GetApproachTowardsUsGuess(iPlayer);
		if iApproach ~= MajorCivApproachTypes.MAJOR_CIV_APPROACH_HOSTILE then
			return "VVNoireSceneDynamicShockUltra.dds"
		end
	end

	return nil
end
Events.LoadScreenClose.Add(function () LuaEvents.AddFunctionToLeaderSceneTable(NoireSpecialLeaderscene) end)


function GetRandomDiploString(sString)
	local locale = "Language_" ..Locale.GetCurrentLanguage().Type
	local t = {}
	for row in DB.Query("SELECT * FROM "..locale.." WHERE Tag LIKE ('"..sString.."')") do
		t[#t + 1] = row.Text
	end
	if #t > 0 then
		return t[Game.Rand(#t, "Random Text Roll") + 1]
	end
end

local bSpecialOverride = false
--Experimental: Just-in-Time addition of text if player is Iris
function OnNoireDialogWithIris(iPlayer, iDiploUIState, szLeaderMessage, iAnimation, iData)
	local sString;
	if tUDNoires[iPlayer] then
		local iActivePlayer = Game:GetActivePlayer()
		local pActivePlayer = Players[iActivePlayer]
		if pActivePlayer:GetLeaderType() == iIrisHeart and not Teams[pActivePlayer:GetTeam()]:IsAtWar(Players[iPlayer]:GetTeam()) then
			if iDiploUIState == DiploUIStateTypes.DIPLO_UI_STATE_DEFAULT_ROOT then
				if szLeaderMessage == Locale.ConvertTextKey("TXT_KEY_UD_VS_PLUTIA_UDNOIRE_FIRSTGREETING_1") then
					sString = Locale.ConvertTextKey("TXT_KEY_UD_VS_IRIS_HEART_UDNOIRE_FIRSTGREETING_1")
				else
					local iApproach = pActivePlayer:GetApproachTowardsUsGuess(iPlayer);
					if iApproach == MajorCivApproachTypes.MAJOR_CIV_APPROACH_HOSTILE then
						sString = GetRandomDiploString("TXT_KEY_UD_VS_IRIS_HEART_UDNOIRE_GREETING_HOSTILE%")
					else
						sString = GetRandomDiploString("TXT_KEY_UD_VS_IRIS_HEART_UDNOIRE_GREETING_POLITE%")
					end
				end
			elseif iDiploUIState == DiploUIStateTypes.DIPLO_UI_STATE_BLANK_DISCUSSION_MEAN_HUMAN and bSpecialOverride == true then
				sString = GetRandomDiploString("TXT_KEY_UD_VS_PLUTIA_UDNOIRE_TRANSFORMED%")
			end
		end
	end

	if sString then
		local speechBox = ContextPtr:LookUpControl("/LeaderHeadRoot/LeaderSpeech")
		if speechBox then
			speechBox:SetText(sString)
			local border = ContextPtr:LookUpControl("/LeaderHeadRoot/LeaderSpeechBorderFrame")
			local frame = ContextPtr:LookUpControl("/LeaderHeadRoot/LeaderSpeechFrame")
			if border and frame then
			local contentSize = speechBox:GetSizeY() + 48;
				border:SetSizeY( contentSize );
				frame:SetSizeY( contentSize - 4 );
			end
		end
		local speechBox2 = ContextPtr:LookUpControl("/LeaderHeadRoot/DiscussionDialog/LeaderSpeech")
		if speechBox2 then
			speechBox2:SetText(sString)
			local border2 = ContextPtr:LookUpControl("/LeaderHeadRoot/DiscussionDialog/LeaderSpeechBorderFrame")
			local frame2 = ContextPtr:LookUpControl("/LeaderHeadRoot/DiscussionDialog/LeaderSpeechFrame")
			if border2 and frame2 then
			local contentSize = speechBox:GetSizeY() + 48;
				border2:SetSizeY( contentSize );
				frame2:SetSizeY( contentSize - 4 );
			end
		end	
	end
	bSpecialOverride = false
end

--UD Noire sends a diplo message as soon as Plutia transforms to Iris.
function OnTransformedNoireSpecialMessage(iPlayer, bHDDOn)
	print("OnTransformedNoireSpecialMessage")
	if bHDDOn == true and iPlayer == Game:GetActivePlayer() then
		local pPlayer = Players[iPlayer]
		if pPlayer:GetLeaderType() == iIrisHeart then
			local pTeam = Teams[pPlayer:GetTeam()]
			for k, v in pairs(tUDNoires) do
				local pLoop = Players[k]
				if pLoop:IsAlive() and not pLoop:IsHuman() and pLoop:GetLeaderType() == iNoireUltra and pTeam:IsHasMet(pLoop:GetTeam()) then
					bSpecialOverride = true
					Game.DoFromUIDiploEvent(7, k, 0, 0);
				end
			end
		end
	end
end

if iIrisHeart then
	Events.AILeaderMessage.Add(OnNoireDialogWithIris)
	LuaEvents.VV_ConvertHDNLeader.Add(OnTransformedNoireSpecialMessage)
end