ALTER TABLE Traits ADD COLUMN 'DOFOnPeaceTreaty' BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE Traits ADD COLUMN 'SiegeUnitsDefenseBonus' BOOLEAN DEFAULT false NOT NULL;
ALTER TABLE GreatWorks ADD COLUMN 'LostLogiaBuilding' TEXT DEFAULT NULL;