INSERT INTO Colors
			(Type,												Red,	Green,	Blue,	Alpha)
VALUES
			('COLOR_PLAYER_THIRD_STREET_SAINTS_ICON',			0.59,	0.59,	0.59,	1.0),
			('COLOR_PLAYER_THIRD_STREET_SAINTS_BACKGROUND',		0.47,	0.11,	0.92,	1.0);


INSERT INTO PlayerColors
			(Type,												PrimaryColor,										SecondaryColor,									TextColor)
VALUES		('PLAYERCOLOR_THIRD_STREET_SAINTS',					'COLOR_PLAYER_THIRD_STREET_SAINTS_ICON',			'COLOR_PLAYER_THIRD_STREET_SAINTS_BACKGROUND',	'COLOR_PLAYER_WHITE_TEXT');