INSERT INTO Audio_Sounds
			(SoundID,										Filename,			LoadType)
VALUES		('SND_LEADER_MUSIC_PIERCE_WASHINGTON_PEACE',	'SRTTPiercePeace',	'Streamed'),
			('SND_LEADER_MUSIC_PIERCE_WASHINGTON_WAR',		'SRTTPierceWar',	'Streamed'),
			('SND_SRTT_RIM_JOBS_MUSIC',						'SRTTCribMusic',	'Streamed'),
			('SND_SRTT_RIM_JOBS_SELECT_SOUND',				'SRTTAirWrench',	'DynamicResident');

INSERT INTO Audio_2DSOUNDS
			(ScriptID,										SoundID,
			SoundType,			MaxVolume,	MinVolume,	IsMusic)
VALUES		('AS2D_LEADER_MUSIC_PIERCE_WASHINGTON_PEACE',	'SND_LEADER_MUSIC_PIERCE_WASHINGTON_PEACE',
			'GAME_MUSIC',		90,			90,			1),
			('AS2D_LEADER_MUSIC_PIERCE_WASHINGTON_WAR',		'SND_LEADER_MUSIC_PIERCE_WASHINGTON_WAR',
			'GAME_MUSIC',		90,			90,			1),
			('AS2D_SRTT_RIM_JOBS_MUSIC',					'SND_SRTT_RIM_JOBS_MUSIC',
			'GAME_MUSIC',		90,			90,			1),
			('AS2D_SRTT_RIM_JOBS_SELECT_SOUND',				'SND_SRTT_RIM_JOBS_SELECT_SOUND',
			'GAME_SFX',		50,			50,			1);
