INSERT INTO DecisionsAddin_Support
			(FileName)
VALUES		('NemesisDecisions.lua');

INSERT INTO BuildingClasses
			(Type,												DefaultBuilding)
VALUES		('BUILDINGCLASS_DECISIONS_NEMESIS_FREE_WINDMILL',	'BUILDING_DECISIONS_NEMESIS_FREE_WINDMILL'),
			('BUILDINGCLASS_DECISIONS_NEMESIS_FREE_GARDEN',		'BUILDING_DECISIONS_NEMESIS_FREE_GARDEN'),
			('BUILDINGCLASS_DECISIONS_NEMESIS_FREE_SPY',		'BUILDING_DECISIONS_NEMESIS_FREE_SPY');


INSERT INTO Buildings
			(Type,										BuildingClass,	
			Cost,	FaithCost,	GreatWorkCount, PrereqTech, NeverCapture,	NukeImmune)
VALUES		('BUILDING_DECISIONS_NEMESIS_FREE_WINDMILL',		'BUILDINGCLASS_DECISIONS_NEMESIS_FREE_WINDMILL',
			-1,		-1,			-1,				null,		1,				1),
			('BUILDING_DECISIONS_NEMESIS_FREE_GARDEN',	'BUILDINGCLASS_DECISIONS_NEMESIS_FREE_GARDEN',
			-1,		-1,			-1,				null,		1,				1),
			('BUILDING_DECISIONS_NEMESIS_FREE_SPY',				'BUILDINGCLASS_DECISIONS_NEMESIS_FREE_SPY',
			-1,		-1,			-1,				null,		1,				1);


UPDATE Buildings
SET FreeBuildingThisCity = 'BUILDINGCLASS_GARDEN'
WHERE Type = 'BUILDING_DECISIONS_NEMESIS_FREE_GARDEN';

UPDATE Buildings
SET FreeBuildingThisCity = 'BUILDINGCLASS_WINDMILL'
WHERE Type = 'BUILDING_DECISIONS_NEMESIS_FREE_WINDMILL';

UPDATE Buildings
SET ExtraSpies = 1
WHERE Type = 'BUILDING_DECISIONS_NEMESIS_FREE_SPY';