INSERT INTO DecisionsAddin_Support
			(FileName)
VALUES		('RecluseDecisions.lua');

INSERT INTO UnitPromotions
			(Type,											Description,								Help,						
			CannotBeChosen,		Sound,	PortraitIndex,	IconAtlas,	PediaType,	PediaEntry)
SELECT		('PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER'),					('TXT_KEY_PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER'),		('TXT_KEY_PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER_HELP'),
			CannotBeChosen,		Sound,	PortraitIndex,	IconAtlas,	PediaType,	('TXT_KEY_PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER')
FROM UnitPromotions	WHERE (Type = 'PROMOTION_STEAM_POWERED');

UPDATE UnitPromotions
SET FriendlyLandsModifier = 20
WHERE Type = 'PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER';


INSERT INTO Policies
			(Type,												BarbarianCombatBonus)
VALUES		('PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER_1',	15),
			('PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER_2',	30),
			('PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER_3',	45),
			('PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER_4',	60),
			('PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER_5',	75),
			('PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER_6',	90),
			('PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER_7',	105),
			('PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER_8',	120),
			('PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER_9',	135),
			('PROMOTION_DECISIONS_RECLUSE_APPOINT_ARBITER_10',	150);