INSERT INTO MG_ActionStates
			(Type,								Description,								Turns)
VALUES
			('MGACTIONSTATE_ACTIVE',			'TXT_KEY_MGACTIONSTATE_ACTIVE',				-1),
			('MGACTIONSTATE_DEAD',				'TXT_KEY_MGACTIONSTATE_DEAD',				-1),
			('MGACTIONSTATE_WITCH',				'TXT_KEY_MGACTIONSTATE_WITCH',				-1),
			('MGACTIONSTATE_CYCLING',			'TXT_KEY_MGACTIONSTATE_CYCLING',			-1),
			('MGACTIONSTATE_WITCH_HUNT',		'TXT_KEY_MGACTIONSTATE_WITCH_HUNT',			 1),
			('MGACTIONSTATE_FREEZER',			'TXT_KEY_MGACTIONSTATE_FREEZER',			-1),
			('MGACTIONSTATE_RETURNED_NORMAL',	'TXT_KEY_MGACTIONSTATE_RETURNED_NORMAL',	-1),
			('MGACTIONSTATE_VACATIONING',		'TXT_KEY_MGACTIONSTATE_VACATIONING',		5),
			('MGACTIONSTATE_DEFECTING',			'TXT_KEY_MGACTIONSTATE_DEFECTING',			3),
			('MGACTIONSTATE_WRITING_HOME',		'TXT_KEY_MGACTIONSTATE_WRITING_HOME',		3),
			('MGACTIONSTATE_SPARRING',			'TXT_KEY_MGACTIONSTATE_SPARRING',			3);

UPDATE MG_ActionStates
SET ReturnMapFunctionTag = 'WITCH_HUNT'
WHERE Type='MGACTIONSTATE_WITCH_HUNT';

UPDATE MG_ActionStates
SET LeaveMapFunctionTag = 'VACATION', ReturnMapFunctionTag = 'VACATION'
WHERE Type='MGACTIONSTATE_VACATION';
