CREATE TABLE IF NOT EXISTS COMMUNITY(Type, Value);

UPDATE Buildings
SET UnculturedHappinessChange = (SELECT UnculturedHappinessChange FROM Buildings WHERE Type = 'BUILDING_COLOSSEUM'), Help = 'TXT_KEY_BUILDING_VV_LEANBOX_ARCADE_HELP_CBP'
WHERE Type = 'BUILDING_VV_LEANBOX_ARCADE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );