CREATE TABLE IF NOT EXISTS COMMUNITY(Type, Value);

UPDATE Buildings
SET DefenseHappinessChange = (SELECT IlliteracyHappinessChange FROM Buildings WHERE Type = 'BUILDING_CONSTABLE')
WHERE Type = 'BUILDING_VV_DRM_TOWER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );