INSERT INTO DecisionsAddin_Support
			(FileName)
VALUES		('PMMMMamiDecisions.lua');

INSERT INTO BuildingClasses
			(Type,	DefaultBuilding)
VALUES		('BUILDINGCLASS_DECISIONS_MAMI_DUMMY', 'BUILDING_DECISIONS_MAMI_DUMMY');

INSERT INTO Buildings
			(Type,										BuildingClass,	
			Cost,	FaithCost,	GreatWorkCount, PrereqTech, NeverCapture,	NukeImmune)
VALUES		('BUILDING_DECISIONS_MAMI_DUMMY',		'BUILDINGCLASS_DECISIONS_MAMI_DUMMY',
			-1,		-1,			-1,				null,		1,				1);

INSERT INTO Policies
			(Type,										Description)
VALUES		('POLICY_DECISIONS_MAMI_JAPANESE',			'TXT_KEY_DECISIONS_MAMI_JAPANESE'),
			('POLICY_DECISIONS_MAMI_ITALIAN',			'TXT_KEY_DECISIONS_MAMI_ITALIAN'),
			('POLICY_DECISIONS_MAMI_MAMMIE_DOCTRINE',	'TXT_KEY_DECISIONS_MAMI_MAMMIE_DOCTRINE');

UPDATE Policies
SET GreatWriterRateModifier = 25, GreatArtistRateModifier = 25, GreatMusicianRateModifier = 25
WHERE Type = 'POLICY_DECISIONS_MAMI_ITALIAN';

UPDATE Policies
SET GreatWriterRateModifier = -25, GreatArtistRateModifier = -25, GreatMusicianRateModifier = -25
WHERE Type = 'POLICY_DECISIONS_MAMI_JAPANESE';

UPDATE Policies
SET PolicyCostModifier = 10, MinorFriendshipMinimum = 10
WHERE Type = 'POLICY_DECISIONS_MAMI_MAMMIE_DOCTRINE';

INSERT INTO Policy_YieldModifiers
			(PolicyType,						YieldType,			Yield)
VALUES		('POLICY_DECISIONS_MAMI_JAPANESE',	'YIELD_SCIENCE',	10),
			('POLICY_DECISIONS_MAMI_JAPANESE',	'YIELD_CULTURE',	-20),
			('POLICY_DECISIONS_MAMI_ITALIAN',	'YIELD_SCIENCE',	-10),
			('POLICY_DECISIONS_MAMI_ITALIAN',	'YIELD_CULTURE',	20);

INSERT INTO Policy_BuildingClassTourismModifiers	
			(PolicyType,						BuildingClassType,						TourismModifier)
VALUES		('POLICY_DECISIONS_MAMI_JAPANESE',	'BUILDINGCLASS_DECISIONS_MAMI_DUMMY',	-20),
			('POLICY_DECISIONS_MAMI_ITALIAN',	'BUILDINGCLASS_DECISIONS_MAMI_DUMMY',	20);

INSERT INTO Policy_SpecialistExtraYields
			(PolicyType,						YieldType,			Yield)
VALUES		('POLICY_DECISIONS_MAMI_JAPANESE',	'YIELD_PRODUCTION',	1),
			('POLICY_DECISIONS_MAMI_ITALIAN',	'YIELD_CULTURE',	1);

UPDATE Traits
SET FreeBuilding = 'BUILDING_DECISIONS_MAMI_DUMMY'
WHERE Type = 'TRAIT_FRIENDSHIP_PRODUCTION_BONUS';

INSERT INTO DiploModifiers
			(Type,											Description)
VALUES		('DIPLOMODIFIER_PMMM_DECISIONS_MAMI_FROM_MALE',	'TXT_KEY_DIPLOMODIFIER_PMMM_DECISIONS_MAMI_FROM_MALE'),
			('DIPLOMODIFIER_PMMM_DECISIONS_MAMI_FROM_MG',	'TXT_KEY_DIPLOMODIFIER_PMMM_DECISIONS_MAMI_FROM_MG'),
			('DIPLOMODIFIER_PMMM_DECISIONS_MAMI_TO_MAMI',	'TXT_KEY_DIPLOMODIFIER_PMMM_DECISIONS_MAMI_TO_MAMI');