INSERT INTO DecisionsAddin_Support		
			(FileName)
VALUES		('MikuDecisions.lua');

INSERT INTO Audio_Sounds
			(SoundID,											Filename,							LoadType)
VALUES		('SND_GREAT_MUSICIAN_VOCALOID_DECISIONS_HPMC',		'HappinessAndPeaceOfMindCommittee',	'Streamed'),
			('SND_GREAT_MUSICIAN_VOCALOID_DECISIONS_UTAULOID',	'Fukkireta',						'Streamed');

INSERT INTO Audio_2DSounds
			(ScriptID,											SoundID,											SoundType,				TaperSoundtrackVolume)
VALUES		('AS2D_GREAT_MUSICIAN_VOCALOID_DECISIONS_HPMC',		'SND_GREAT_MUSICIAN_VOCALOID_DECISIONS_HPMC',		'GAME_MUSIC_STINGS',	0.0),
			('AS2D_GREAT_MUSICIAN_VOCALOID_DECISIONS_UTAULOID', 'SND_GREAT_MUSICIAN_VOCALOID_DECISIONS_UTAULOID',	'GAME_MUSIC_STINGS',	0.0);

INSERT INTO GreatWorks
			(Type,										GreatWorkClassType,		Description,										Image,
			Audio,												BonusFromOtherCivsInfluenced)
VALUES		('GREAT_WORK_VOCALOID_DECISIONS_HPMC',		'GREAT_WORK_MUSIC',		'TXT_KEY_GREAT_WORK_VOCALOID_DECISIONS_HPMC',		'HappinessAndPeaceOfMindCommittee.dds',
			'AS2D_GREAT_MUSICIAN_VOCALOID_DECISIONS_HPMC',	1),
			('GREAT_WORK_VOCALOID_DECISIONS_UTAULOID',	'GREAT_WORK_MUSIC',		'TXT_KEY_GREAT_WORK_VOCALOID_DECISIONS_FUKKIRETA',	'Fukkireta.dds',
			'AS2D_GREAT_MUSICIAN_VOCALOID_DECISIONS_UTAULOID',	1);

INSERT INTO BuildingClasses 	
			(Type, 						 				DefaultBuilding, 					Description, 								MaxPlayerInstances)
VALUES		('BUILDINGCLASS_DECISIONS_MIKU_HPMC',		'BUILDING_DECISIONS_MIKU_HPMC', 	'TXT_KEY_DECISIONS_BUILDING_MIKU_HPMC',		-1),
			('BUILDINGCLASS_DECISIONS_MIKU_UTAULOID',	'BUILDING_DECISIONS_MIKU_UTAULOID', 'TXT_KEY_DECISIONS_BUILDING_MIKU_UTAULOID',	-1);


INSERT INTO Buildings 	
			(Type, 						 		BuildingClass, 							Description,								Civilopedia,											Help,
			Strategy,			Cost,	PrereqTech, 	ConquestProb,	IconAtlas, 					PortraitIndex, NeverCapture, NukeImmune)
VALUES		('BUILDING_DECISIONS_MIKU_HPMC', 	'BUILDINGCLASS_DECISIONS_MIKU_HPMC',	'TXT_KEY_DECISIONS_BUILDING_MIKU_HPMC',		'TXT_KEY_DECISIONS_BUILDING_MIKU_HPMC_CIVILOPEDIA',		'TXT_KEY_DECISIONS_BUILDING_MIKU_HPMC_HELP',
			null,				-1,  	null,			100,			'EXPANSION_BW_ATLAS_1',		11,				1,			1),
			('BUILDING_DECISIONS_MIKU_UTAULOID','BUILDINGCLASS_DECISIONS_MIKU_UTAULOID','TXT_KEY_DECISIONS_BUILDING_MIKU_UTAULOID',	'TXT_KEY_DECISIONS_BUILDING_MIKU_UTAULOID_CIVILOPEDIA',	'TXT_KEY_DECISIONS_BUILDING_MIKU_UTAULOID_HELP',
			null,				-1,  	null,			100,			'EXPANSION2_BUILDING_ATLAS',6,				0,			1);


UPDATE Buildings
SET GreatWorkSlotType = 'GREAT_WORK_SLOT_MUSIC', GreatWorkCount = 1
WHERE Type = 'BUILDING_DECISIONS_MIKU_HPMC' OR Type = 'BUILDING_DECISIONS_MIKU_UTAULOID';

UPDATE Buildings
SET UnhappinessModifier = -20, FreeGreatWork='GREAT_WORK_VOCALOID_DECISIONS_HPMC'
WHERE Type = 'BUILDING_DECISIONS_MIKU_HPMC';

UPDATE Buildings
SET SpecialistType = 'SPECIALIST_MUSICIAN', SpecialistCount = 3, FreeGreatWork='GREAT_WORK_VOCALOID_DECISIONS_UTAULOID'
WHERE Type = 'BUILDING_DECISIONS_MIKU_UTAULOID';


