INSERT INTO Colors
			(Type,										Red,		Green,		Blue,		Alpha)
VALUES
			('COLOR_PLAYER_JJBA_AMERICA_ICON',			0.91765,	0.41568,	0.70588,	1.0),
			('COLOR_PLAYER_JJBA_AMERICA_BACKGROUND',	0.69411,	0.94509,	0.98431,	1.0);


INSERT INTO PlayerColors
			(Type,							PrimaryColor,						SecondaryColor,							TextColor)
VALUES		('PLAYERCOLOR_JJBA_AMERICA',	'COLOR_PLAYER_JJBA_AMERICA_ICON',	'COLOR_PLAYER_JJBA_AMERICA_BACKGROUND',	'COLOR_PLAYER_WHITE_TEXT');