INSERT INTO DecisionsAddin_Support
			(FileName)
VALUES		('FunnyValentineDecisions.lua');

INSERT INTO BuildingClasses 	
			(Type, 						 		 						DefaultBuilding, 										Description)
VALUES		('BUILDINGCLASS_DECISIONS_FUNNY_VALENTINE_WINTER_CATFISH',	'BUILDING_DECISIONS_FUNNY_VALENTINE_WINTER_CATFISH', 	'TXT_KEY_DECISIONS_FUNNY_VALENTINE_WINTER_CATFISH');

INSERT INTO Buildings
			(Type,													Description,										BuildingClass,	
			Cost,	FaithCost,	GreatWorkCount, PrereqTech, NeverCapture,	NukeImmune)
VALUES		('BUILDING_DECISIONS_FUNNY_VALENTINE_WINTER_CATFISH',	'TXT_KEY_DECISIONS_FUNNY_VALENTINE_WINTER_CATFISH',	'BUILDINGCLASS_DECISIONS_FUNNY_VALENTINE_WINTER_CATFISH',
			-1,		-1,			-1,				null,		1,				1);

INSERT INTO Building_ResourceYieldChanges
			(BuildingType,											ResourceType,		YieldType,		Yield)
VALUES		('BUILDING_DECISIONS_FUNNY_VALENTINE_WINTER_CATFISH',	'RESOURCE_FISH',	'YIELD_GOLD',	3),
			('BUILDING_DECISIONS_FUNNY_VALENTINE_WINTER_CATFISH',	'RESOURCE_FISH',	'YIELD_CULTURE',3),
			('BUILDING_DECISIONS_FUNNY_VALENTINE_WINTER_CATFISH',	'RESOURCE_FISH',	'YIELD_FOOD',	3);



INSERT INTO EventsAddin_Support
			(FileName)
VALUES		('FunnyValentineEvents.lua');



INSERT INTO Policies
			(Type,												Description)
VALUES		('POLICY_DECISIONS_FUNNY_VALENTINE_UNION',			'TXT_KEY_POLICY_DECISIONS_FUNNY_VALENTINE_UNION'),
			('POLICY_DECISIONS_FUNNY_VALENTINE_CONFEDERACY',	'TXT_KEY_POLICY_DECISIONS_FUNNY_VALENTINE_CONFEDERACY');


UPDATE Policies
SET UnhappinessMod = -10, PlotCultureExponentModifier = -25, WorkerSpeedModifier = -25
WHERE Type = 'POLICY_DECISIONS_FUNNY_VALENTINE_UNION';

UPDATE Policies
SET UnhappinessMod = 10, PolicyCostModifier = 10
WHERE Type = 'POLICY_DECISIONS_FUNNY_VALENTINE_CONFEDERACY';


INSERT INTO Policy_FreeUnitClasses
			(PolicyType,										UnitClassType,			Count)
VALUES		('POLICY_DECISIONS_FUNNY_VALENTINE_CONFEDERACY',	'UNITCLASS_SETTLER',	1),
			('POLICY_DECISIONS_FUNNY_VALENTINE_CONFEDERACY',	'UNITCLASS_WORKER',		1);