INSERT INTO Audio_Sounds
			(SoundID,									Filename,		LoadType)
VALUES		('SND_LEADER_MUSIC_VV_NOIRE_PEACE',			'VVNoirePeace',	'Streamed'),
			('SND_LEADER_MUSIC_VV_NOIRE_WAR',			'VVNoireWar',	'Streamed'),
			('SND_LEADER_MUSIC_VV_NOIRE_ULTRA_PEACE',	'VVNoireUPeace','Streamed'),
			('SND_LEADER_MUSIC_VV_NOIRE_ULTRA_WAR',		'VVNoireUWar',	'Streamed');

INSERT INTO Audio_2DSounds
			(ScriptID,									SoundID,
			SoundType,			MaxVolume,	MinVolume,	IsMusic)
VALUES		('AS2D_LEADER_MUSIC_VV_NOIRE_PEACE',		'SND_LEADER_MUSIC_VV_NOIRE_PEACE',
			'GAME_MUSIC',		55,			55,			1),
			('AS2D_LEADER_MUSIC_VV_NOIRE_WAR',			'SND_LEADER_MUSIC_VV_NOIRE_WAR',
			'GAME_MUSIC',		35,			35,			1),
			('AS2D_LEADER_MUSIC_VV_BLACK_HEART_PEACE',	'SND_LEADER_MUSIC_VV_NOIRE_PEACE',
			'GAME_MUSIC',		55,			55,			1),
			('AS2D_LEADER_MUSIC_VV_BLACK_HEART_WAR',	'SND_LEADER_MUSIC_VV_NOIRE_WAR',
			'GAME_MUSIC',		35,			35,			1),
			('AS2D_LEADER_MUSIC_VV_NOIRE_ULTRA_PEACE',	'SND_LEADER_MUSIC_VV_NOIRE_ULTRA_PEACE',
			'GAME_MUSIC',		35,			35,			1),
			('AS2D_LEADER_MUSIC_VV_NOIRE_ULTRA_WAR',	'SND_LEADER_MUSIC_VV_NOIRE_ULTRA_WAR',
			'GAME_MUSIC',		55,			55,			1),
			('AS2D_LEADER_MUSIC_VV_BLACK_HEART_ULTRA_PEACE','SND_LEADER_MUSIC_VV_NOIRE_ULTRA_PEACE',
			'GAME_MUSIC',		35,			35,			1),
			('AS2D_LEADER_MUSIC_VV_BLACK_HEART_ULTRA_WAR',	'SND_LEADER_MUSIC_VV_NOIRE_ULTRA_WAR',
			'GAME_MUSIC',		55,			55,			1);


