INSERT INTO Colors
			(Type,											Red,		Green,		Blue,		Alpha)
VALUES
			('COLOR_PLAYER_VV_LASTATION_UN_ICON',			1.0,		1.0,		1.0,		1.0),
			('COLOR_PLAYER_VV_LASTATION_UN_BACKGROUND',		0.517647,	0.513725,	0.568627,	1.0);


INSERT INTO PlayerColors
			(Type,							PrimaryColor,							SecondaryColor,								TextColor)
VALUES		('PLAYERCOLOR_VV_LASTATION_UN',	'COLOR_PLAYER_VV_LASTATION_UN_ICON',	'COLOR_PLAYER_VV_LASTATION_UN_BACKGROUND',	'COLOR_PLAYER_WHITE_TEXT');