INSERT INTO Audio_Sounds
			(SoundID,									Filename,		LoadType)
VALUES		('SND_LEADER_MUSIC_VV_BLANC_PEACE',			'VVBlancPeace',	'Streamed'),
			('SND_LEADER_MUSIC_VV_BLANC_WAR',			'VVBlancWar',	'Streamed'),
			('SND_LEADER_MUSIC_VV_BLANC_ULTRA_PEACE',	'VVBlancUPeace',	'Streamed'),
			('SND_LEADER_MUSIC_VV_BLANC_ULTRA_WAR',		'VVBlancUWar',	'Streamed');

INSERT INTO Audio_2DSounds
			(ScriptID,									SoundID,
			SoundType,			MaxVolume,	MinVolume,	IsMusic)
VALUES		('AS2D_LEADER_MUSIC_VV_BLANC_PEACE',			'SND_LEADER_MUSIC_VV_BLANC_PEACE',
			'GAME_MUSIC',		50,			50,			1),
			('AS2D_LEADER_MUSIC_VV_BLANC_WAR',				'SND_LEADER_MUSIC_VV_BLANC_WAR',
			'GAME_MUSIC',		50,			50,			1),
			('AS2D_LEADER_MUSIC_VV_WHITE_HEART_PEACE',		'SND_LEADER_MUSIC_VV_BLANC_PEACE',
			'GAME_MUSIC',		50,			50,			1),
			('AS2D_LEADER_MUSIC_VV_WHITE_HEART_WAR',		'SND_LEADER_MUSIC_VV_BLANC_WAR',
			'GAME_MUSIC',		50,			50,			1),
			('AS2D_LEADER_MUSIC_VV_BLANC_ULTRA_PEACE',		'SND_LEADER_MUSIC_VV_BLANC_ULTRA_PEACE',
			'GAME_MUSIC',		50,			50,			1),
			('AS2D_LEADER_MUSIC_VV_BLANC_ULTRA_WAR',		'SND_LEADER_MUSIC_VV_BLANC_ULTRA_WAR',
			'GAME_MUSIC',		50,			50,			1),
			('AS2D_LEADER_MUSIC_VV_WHITE_HEART_ULTRA_PEACE','SND_LEADER_MUSIC_VV_BLANC_ULTRA_PEACE',
			'GAME_MUSIC',		50,			50,			1),
			('AS2D_LEADER_MUSIC_VV_WHITE_HEART_ULTRA_WAR',	'SND_LEADER_MUSIC_VV_BLANC_ULTRA_WAR',
			'GAME_MUSIC',		50,			50,			1);


