INSERT INTO Colors
			(Type,											Red,		Green,		Blue,		Alpha)
VALUES
			('COLOR_PLAYER_VV_PLANEPTUNE_NG_ICON',			0.392157,	0.282353,	0.674510,	1.0),
			('COLOR_PLAYER_VV_PLANEPTUNE_NG_BACKGROUND',	0.941176,	0.941176,	0.941176,	1.0);


INSERT INTO PlayerColors
			(Type,						PrimaryColor,					SecondaryColor,							TextColor)
VALUES		('PLAYERCOLOR_VV_PLANEPTUNE_NG',	'COLOR_PLAYER_VV_PLANEPTUNE_NG_ICON',	'COLOR_PLAYER_VV_PLANEPTUNE_NG_BACKGROUND',	'COLOR_PLAYER_WHITE_TEXT');