INSERT INTO Colors
			(Type,											Red,		Green,		Blue,		Alpha)
VALUES
			('COLOR_PLAYER_VV_PLANEPTUNE_ICON',			1.0,		1.0,		1.0,		1.0),
			('COLOR_PLAYER_VV_PLANEPTUNE_BACKGROUND',	0.686274,	0.607843,	0.850980,	1.0);


INSERT INTO PlayerColors
			(Type,								PrimaryColor,					SecondaryColor,							TextColor)
VALUES		('PLAYERCOLOR_VV_PLANEPTUNE',	'COLOR_PLAYER_VV_PLANEPTUNE_ICON',	'COLOR_PLAYER_VV_PLANEPTUNE_BACKGROUND',	'COLOR_PLAYER_WHITE_TEXT');