INSERT INTO Audio_Sounds
			(SoundID,									Filename,			LoadType)
VALUES		('SND_LEADER_MUSIC_VV_NEPGEAR_PEACE',		'VVNepgearPeace',	'Streamed'),
			('SND_LEADER_MUSIC_VV_NEPGEAR_WAR',			'VVNepgearWar',		'Streamed');

INSERT INTO Audio_2DSounds
			(ScriptID,									SoundID,
			SoundType,			MaxVolume,	MinVolume,	IsMusic)
VALUES		('AS2D_LEADER_MUSIC_VV_NEPGEAR_PEACE',		'SND_LEADER_MUSIC_VV_NEPGEAR_PEACE',
			'GAME_MUSIC',		50,			50,			1),
			('AS2D_LEADER_MUSIC_VV_NEPGEAR_WAR',		'SND_LEADER_MUSIC_VV_NEPGEAR_WAR',
			'GAME_MUSIC',		50,			50,			1),
			('AS2D_LEADER_MUSIC_VV_PURPLE_SISTER_PEACE','SND_LEADER_MUSIC_VV_NEPGEAR_PEACE',
			'GAME_MUSIC',		50,			50,			1),
			('AS2D_LEADER_MUSIC_VV_PURPLE_SISTER_WAR',	'SND_LEADER_MUSIC_VV_NEPGEAR_WAR',
			'GAME_MUSIC',		50,			50,			1);


