INSERT INTO Religions
			(Type,						Description,						Civilopedia,							IconAtlas,						PortraitIndex,	IconString)
VALUES		('RELIGION_VV_PLANEPTUNE',	'TXT_KEY_RELIGION_VV_PLANEPTUNE',	'TXT_KEY_RELIGION_VV_PLANEPTUNE_PEDIA',	'RELIGION_ATLAS_VV_PLANEPTUNE',	0,				'[ICON_VV_PURPLE_HEART_RELIGION]');