INSERT INTO Colors
			(Type,											Red,		Green,		Blue,		Alpha)
VALUES
			('COLOR_PLAYER_VV_PLANEPTUNE_PL_ICON',			0.858824,	0.619608,	0.764706,	1.0),
			('COLOR_PLAYER_VV_PLANEPTUNE_PL_BACKGROUND',	0.764706,	0.941176,	0.952941,	1.0);


INSERT INTO PlayerColors
			(Type,								PrimaryColor,							SecondaryColor,								TextColor)
VALUES		('PLAYERCOLOR_VV_PLANEPTUNE_PL',	'COLOR_PLAYER_VV_PLANEPTUNE_PL_ICON',	'COLOR_PLAYER_VV_PLANEPTUNE_PL_BACKGROUND',	'COLOR_PLAYER_WHITE_TEXT');