INSERT INTO Missions
			(Type,Description,Help,DisabledHelp,EntityEventType,Time,OrderPriority,Visible,IconIndex,IconAtlas)
SELECT		('MISSION_MSF_OSP_UPGRADE'),('TXT_KEY_ENEMY_TERRITORY_UPGRADE_BUTTON_TITLE'),('TXT_KEY_ENEMY_TERRITORY_UPGRADE_BUTTON_TEXT'),('TXT_KEY_MSF_OSP_UPGRADE_DISABLED_TEXT_DVMC'),EntityEventType,Time,200,Visible,38,('UNIT_ACTION_ATLAS')
FROM Missions WHERE Type = 'MISSION_RANGE_ATTACK';


INSERT INTO Missions
			(Type,Description,Help,DisabledHelp,EntityEventType,Time,OrderPriority,Visible,IconIndex,IconAtlas)
SELECT		('MISSION_MSF_MG_UPGRADE'),('TXT_KEY_METAL_GEAR_UPGRADE_BUTTON_TITLE'),('TXT_KEY_METAL_GEAR_UPGRADE_BUTTON_TEXT'),('TXT_KEY_MSF_MG_UPGRADE_BUTTON_DISABLED_TEXT'),EntityEventType,Time,200,Visible,36,('UNIT_ACTION_ATLAS')
FROM Missions WHERE Type = 'MISSION_RANGE_ATTACK';