INSERT INTO DecisionsAddin_Support
			(FileName)
VALUES		('PMMMDemonHomuraDecisions.lua');

INSERT INTO BuildingClasses
			(Type,													DefaultBuilding,								NoLimit)
VALUES		('BUILDINGCLASS_DECISION_DEMON_HOMURA_INCUBATOR',		'BUILDING_DECISION_DEMON_HOMURA_INCUBATOR',		1),
			('BUILDINGCLASS_DECISION_DEMON_HOMURA_PACIFY_SELF',		'BUILDING_DECISION_DEMON_HOMURA_PACIFY_SELF',	1),
			('BUILDINGCLASS_DECISION_DEMON_HOMURA_PACIFY_OTHERS',	'BUILDING_DECISION_DEMON_HOMURA_PACIFY_OTHERS',	1);

INSERT INTO Buildings
			(Type,												BuildingClass,	
			Cost,	FaithCost,	GreatWorkCount, PrereqTech, NeverCapture,	NukeImmune)
VALUES		('BUILDING_DECISION_DEMON_HOMURA_INCUBATOR',		'BUILDINGCLASS_DECISION_DEMON_HOMURA_INCUBATOR',
			-1,		-1,			-1,				null,		1,				1),
			('BUILDING_DECISION_DEMON_HOMURA_PACIFY_SELF',		'BUILDINGCLASS_DECISION_DEMON_HOMURA_PACIFY_SELF',
			-1,		-1,			-1,				null,		1,				1),
			('BUILDING_DECISION_DEMON_HOMURA_PACIFY_OTHERS',		'BUILDINGCLASS_DECISION_DEMON_HOMURA_PACIFY_OTHERS',
			-1,		-1,			-1,				null,		1,				1);

UPDATE Buildings
SET UnmoddedHappiness = 1
WHERE Type = 'BUILDING_DECISION_DEMON_HOMURA_INCUBATOR' OR Type = 'BUILDING_DECISION_DEMON_HOMURA_PACIFY_OTHERS';

INSERT INTO Building_YieldModifiers
			(BuildingType,									YieldType,			Yield)
VALUES		('BUILDING_DECISION_DEMON_HOMURA_PACIFY_SELF',	'YIELD_CULTURE',	1),
			('BUILDING_DECISION_DEMON_HOMURA_PACIFY_SELF',	'YIELD_PRODUCTION',	1),
			('BUILDING_DECISION_DEMON_HOMURA_PACIFY_SELF',	'YIELD_SCIENCE',	1),
			('BUILDING_DECISION_DEMON_HOMURA_PACIFY_SELF',	'YIELD_GOLD',		1);