INSERT INTO DecisionsAddin_Support
			(FileName)
VALUES		('PMMMHomuraDecisions.lua');

INSERT INTO Policies
			(Type,										Description)
VALUES		('POLICY_DECISIONS_HOMURA_DEVOTE_MADOKA',	'TXT_KEY_DECISIONS_HOMURA_DEVOTE_MADOKA');

UPDATE Policies
SET MinorFriendshipMinimum = -5
WHERE Type = 'POLICY_DECISIONS_HOMURA_DEVOTE_MADOKA';

INSERT INTO BuildingClasses 	
			(Type, 						 		 			DefaultBuilding, 							Description, 										MaxPlayerInstances)
VALUES		('BUILDINGCLASS_DECISIONS_HOMURA_DEVOTE_MADOKA','BUILDING_DECISIONS_HOMURA_DEVOTE_MADOKA', 	'TXT_KEY_DECISIONS_BUILDING_HOMURA_DEVOTE_MADOKA',	1);


INSERT INTO Buildings 	
			(Type, 						 					BuildingClass, 									Description,										Civilopedia,													Help,													Strategy,			Cost,	PrereqTech, 	ConquestProb,	IconAtlas, 						PortraitIndex)
VALUES		('BUILDING_DECISIONS_HOMURA_DEVOTE_MADOKA', 	'BUILDINGCLASS_DECISIONS_HOMURA_DEVOTE_MADOKA',	'TXT_KEY_DECISIONS_BUILDING_HOMURA_DEVOTE_MADOKA',	'TXT_KEY_DECISIONS_BUILDING_HOMURA_DEVOTE_MADOKA_CIVILOPEDIA',	'TXT_KEY_DECISIONS_BUILDING_HOMURA_DEVOTE_MADOKA_HELP',	null,				-1,  	null,			100,			'CIV_COLOR_ATLAS_MADOKA_TEMP',	3);

UPDATE Buildings
SET UnhappinessModifier = 10
WHERE Type = 'BUILDING_DECISIONS_HOMURA_DEVOTE_MADOKA';

INSERT INTO Building_BuildingClassYieldChanges
			(BuildingType, 									BuildingClassType,			YieldType, 				YieldChange)
VALUES		('BUILDING_DECISIONS_HOMURA_DEVOTE_MADOKA', 	'BUILDINGCLASS_MONUMENT',		'YIELD_FAITH', 			2);


INSERT INTO DiploModifiers
			(Type,															Description)
VALUES		('DIPLOMODIFIER_PMMM_DECISIONS_HOMURA_POSITIVE_TO_HOMURA',		'TXT_KEY_DIPLOMODIFIER_PMMM_DECISIONS_HOMURA_POSITIVE_TO_HOMURA'), --"to Homura" means from Madoka to Homura, so it would be seen by a Homura player when mousing over Madoka
			('DIPLOMODIFIER_PMMM_DECISIONS_HOMURA_POSITIVE_TO_MADOKA',		'TXT_KEY_DIPLOMODIFIER_PMMM_DECISIONS_HOMURA_POSITIVE_TO_MADOKA'),
			('DIPLOMODIFIER_PMMM_DECISIONS_HOMURA_NEGATIVE_TO_HOMURA',		'TXT_KEY_DIPLOMODIFIER_PMMM_DECISIONS_HOMURA_NEGATIVE_TO_HOMURA');
